### ISSUE TITLE
Force comments

### ISSUE THREAD

**Issue by cAbtHelectronics** [Part-DB/Part-DB-server#220]
Is making comments mandatory an option?
For example, I want when I get an article delivered I want for the article-history always a comment, for example with the dispatch-note or another comment. I want to “force” the user to describe what happened to the article. 

Overall, a great update of Part-DB, I have been using it since 0.5.4.

**Comment by jbtronics** [comment]
Implemented with the new `ENFORCE_CHANGE_COMMENTS_FOR` option
