### ISSUE TITLE
I can not get it working on Docker on synology NAS

### ISSUE THREAD

**Issue by Tallen-t** [Part-DB/Part-DB-server#240]
I get a database error. 

<img width="613" alt="error" src="https://user-images.githubusercontent.com/37555973/224078055-754f374e-14fa-4d3c-9547-0af0b373b070.png">

**Comment by jbtronics** [comment]
You have to run the database migration command inside your docker container to initialize the database.

See step 3 here: https://docs.part-db.de/installation/installation_docker.html

Basically you have to run `docker exec --user=www-data partdb php bin/console doctrine:migrations:migrate`, where partdb is the name of your docker container.

**Comment by Tallen-t** [comment]
ok. Got it going but now cant see any parts that i have created.\
Nothing in logs
<img width="712" alt="1" src="https://user-images.githubusercontent.com/37555973/224103981-82159e5e-7201-401f-ba2e-9d328de56804.png">
<img width="845" alt="2" src="https://user-images.githubusercontent.com/37555973/224104007-99af8877-636e-4737-bdbb-8545222bf43c.png">

**Comment by Tallen-t** [comment]
6 hours later....
I still can not view my parts, and i noticed that the same problem is occuring on the demo website.
The demo website shows almost a thousand parts but none are viewable

**Comment by jbtronics** [comment]
That's issue #241 
Discussion will be continued there
