### ISSUE TITLE
Cannot see any parts after browser cache clear

### ISSUE THREAD

**Issue by mase76** [Part-DB/Part-DB-server#241]
Hi,
since I cleared my browser cache, I don't see any parts. Everything else, like categories, footprints, etc. is visible. Under "show statistics" I see the correct numer of parts. I cannot see anything in the logs. Also beginning with a fresh database, there are no parts visible after creating one. I am on Debian 11 with Mariadb. The PHP version is 7.4.

**Comment by mase76** [comment]
I did a downgrade to 1.0.3 and the parts are shown again as expected.

**Comment by mase76** [comment]
Seems that 02134dc959a27fc355a257b57e69c55695b3cef9 causes the problem.

**Comment by jbtronics** [comment]
> Seems that [02134dc](https://github.com/Part-DB/Part-DB-server/commit/02134dc959a27fc355a257b57e69c55695b3cef9) causes the problem.

Yeah this seems plausible. If no entry was set data is null, and trying to set anything on it will cause an error in the Browser which fails to load the table.
In my testings I had some old data set, so I didn't notice...

Should be easy to fix.

**Comment by Tallen-t** [comment]
working on demo site.
can you update docker image?

**Comment by mase76** [comment]
I can confirm, that this issue is fixed in v1.1.1.
