### ISSUE TITLE
IC logos unreadable in dark mode

### ISSUE THREAD

**Issue by d-buchmann** [Part-DB/Part-DB-server#242]
Under "Tools->IC Logos", you can not see the logos if you set your instance to dark mode.
As the background of the images is transparent, the foreground color should be white in this case.

**Comment by jbtronics** [comment]
With the latest commit on the master branch the logos are shown white on black background 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/5410681/224506391-f58711b5-24bc-48c3-9bc0-f585f03e315b.png">
