### ISSUE TITLE
How to update Version 1.0.0-alpha running in Docker

### ISSUE THREAD

**Issue by mrWheel** [Part-DB/Part-DB-server#253]
@jbtronics 
Thanks for this incredible tool! My life depends on it as I really won't be able to find any of my stock parts without it!

I'm running Parts-DB in a Docker container. Problem is I don't know much about Docker (just used the image you provided).

How can I update to Parts-DB (running in Docker) to the latest stable version without loosing my data? 

Thanks in advance!

**Comment by jbtronics** [comment]
If you use the default docker-compose.yaml file, it should be enough to just run `docker-compose pull` to pull the new image and restart the containers and run database migration. See here for more info: https://docs.part-db.de/installation/installation_docker.html#update-part-db
