### ISSUE TITLE
After upgrading from legacy version, I can't log in.

### ISSUE THREAD

**Issue by Pyromane** [Part-DB/Part-DB-server#263]
Hello,

I had been using the legacy version almost entirely as an anonymous user and I see this content even without logging in.

When I try to log in as admin, no error message comes up, no matter if I enter the valid admin login or freely invented data, but always end up back at the login screen.

By using
```
php bin/console partdb:users:set-password admin
php bin/console cache:clear
```
I already tried to set a new PW and clear the cache.

/var/log/prod.log does not exist for me, although I have a native installation
/var/log/apache2/partdb_error.log contains no content.
/var/log/apache2/partdb_access.log 
```192.168.0.11 - - [10/Apr/2023:13:23:29 +0000] "POST /en/login HTTP/1.1" 302 1004 "http://192.168.0.18/de/login" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 OPR/95.0.0.0"```
The developer console in the browser doesn't provide great insights from my point of view either: 
![image](https://user-images.githubusercontent.com/5962901/230914872-a93126d1-c512-4bed-a0e8-8e67a90dda38.png)

How can I get more log messages?
Thanks a lot!

**Comment by Pyromane** [comment]
```
 php bin/console partdb:users:list

[INFO] Found 2 users in database.
Users:
======
+----+-----------+------+-------+----------------+----------------+-------+
| ID | Username  | Name | Email | Group          | Login Disabled | Type  |
+----+-----------+------+-------+----------------+----------------+-------+
| 1  | anonymous |      |       | users (ID: 3)  | No             | Local |
| 2  | admin     |      |       | admins (ID: 1) | No             | Local |
+----+-----------+------+-------+----------------+----------------+-------+
```

**Comment by jbtronics** [comment]
> /var/log/prod.log does not exist for me, although I have a native installation

You must not look into the absolute path (so in your file system), but into the `var/log` folder inside your Part-DB installation. There you should find more detailed error messages.

**Comment by IvanBayan** [comment]
@Pyromane have you tried to execute `php bin/console partdb:users:upgrade-permissions-schema`?

**Comment by Pyromane** [comment]
> @Pyromane have you tried to execute `php bin/console partdb:users:upgrade-permissions-schema`?

Thanks for the tip, that was the solution to the problem!

**Comment by jbtronics** [comment]
Im actually surprised (and can't really explain why), that this command did change anything on your problem.

Normally the permission schema migration is done on demand in the next request of a user (so in your case the login). This command is not really needed, it's more intended for debug purposes.

Also your output suggests that nothing on your admin user were changed, so I don't really know what happened.

However I am glad to hear, that it works now.

**Comment by Pyromane** [comment]
My attempts to recreate the whole thing failed, now the migration command is perfectly sufficient and I can log in with my admin password immediately afterwards.

Thanks for your support jbtronics and IvanBayan!
