### ISSUE TITLE
Recursion error on Store Location view

### ISSUE THREAD

**Issue by sunflower-seed** [Part-DB/Part-DB-server#267]
**Describe the bug**

I'm using a standard see-through boxes (german: Kleinteilemagazin) with about 60 cases, which is quite standard for different manufactures. 
So i created a storage location with 60+ sub-location (as any case could be additionally splitted).

When i try to access a this storage location in the storage location view a recursion error happens.
(Quick fix below)

**To Reproduce**

1. Create a storage location with more than 50 sub-locations.
1. Go to Store Locations
2. Click on the parent store location

**Expected behavior**

As i think i use standard boxes for storing my items, PartDB-server should support them flawlessly.

**Analysis**

I found out that in the recursion limit in [AbstractPartsContainingRepository](https://github.com/Part-DB/Part-DB-server/blob/master/src/Repository/AbstractPartsContainingRepository.php#L30) causes the error.

As the current code does not seems very well evolved in my eyes, i suggest du raise the recursion limit to a much higher value.
A value of `100` works for me. It also does not seem to have any performance impact.

**Server Side**

  - Part-DB Version: Part-DB 1.2.0
  - PHP Version: 8.1
  - Database Server : MariaDB 10.6.12

**Comment by jbtronics** [comment]
The implementation of the limit was actually wrong: It limited the number of child elements of a single element (which caused yours problems), not the depth of elements to which we can count (like it was intended).

I fixed the implementation, now you should be fine, as long as you do not have a tree with more than 50 levels of nodes (which would be pretty horrific and most likely cause some visual problems).
