### ISSUE TITLE
Language agnocstic URL - Rewriting does not work with Parameters in URL

### ISSUE THREAD

**Issue by sunflower-seed** [Part-DB/Part-DB-server#268]
**Describe the bug**

PartDB-Server seems to be capable of rewriting URLs without an language given. 
This also works with soft links in URI (# parameters)

But if you have certain parameters in URL they are not transferred.

Later on i'll explain why this might be useful.

**To Reproduce**
Example URLs:

* Working:
  * `https://partdb.local/label/dialog#advanced` changes to `https://partdb.local/de/label/dialog#advanced`
* Not working:
  * `https://partdb.local/label/dialog?target_type=part&target_id=133` changes to `https://partdb.local/de/label/dialog`
  * `https://partdb.local/parts/search?storelocation=1&keyword=MAG01` changes to `https://partdb.local/de/parts/search`

**Expected behavior**

I suggest to keep URI params if you do a redirect from a language agnostic URL.
That makes hot linking between users easier.
I also want to describe another use case where i came up with the problem:
I have a legacy qr code system on my storage items. These contain a URL with the name of the storage location.
I used to rewrite this location url to a e.g. search url for the specific storage location, like `https://partdb.local/de/parts/search?storelocation=1&keyword=STORE1`.
It would make much more sense if i can skip the language on that.

**Server Side**
  - Part-DB Version: Part-DB 1.2.0
  - PHP Version: 8.1
  - Database Server : MariaDB 10.6.12

**Comment by jbtronics** [comment]
Should be fixed in latest master branch version
