### ISSUE TITLE
404 error after storage location deletion

### ISSUE THREAD

**Issue by Pyromane** [Part-DB/Part-DB-server#273]
If you delete the store location e.g. with the ID 475 in the Tools > Store Location (=part-db.herokuapp.com/en/store_location/475/edit), then you are automatically redirected to http://part-db.herokuapp.com/de/store_location/475 and get a 404 error.

**Comment by jbtronics** [comment]
What browser are you using?

Looks a bit like issue #258

**Comment by Pyromane** [comment]
The error exists with FireFox 111.0.1 (64-bit) as well as 112.0 (64-bit).

The problem does not exist with Microsoft Edge version 112.0.1722.48.

**Comment by jbtronics** [comment]
Should be fixed now.

**Comment by Pyromane** [comment]
Yes, it is fixed.
Thanks a lot!
