### ISSUE TITLE
Special  characters

### ISSUE THREAD

**Issue by blue3121** [Part-DB/Part-DB-server#275]
Where are the characters of the entire Greek alphabet (like "omega"  "alpha" and so on) in the list of "notes" ?

Can you add the list also in "Unit symbol" in the "Measurement Unit" section?
The Greek alphabet is fundamental for most of the parameters and formulas used !

Thank You !!!

**Comment by jbtronics** [comment]
I thought greek characters were part of the special symbols list in CKEditor, but it doesnt seems so. Will look into it.

You can type out the most commonly used greek characters on your keyboard in every Part-DB text field by pressing Alt + [Key]. 
For example to make a omega character by pressing Alt + W.
However many of these Alt keys are already assigned to some browser shortcuts, so i will maybe change the key to something else...

**Comment by jbtronics** [comment]
The CKEDITOR special characters plugin now has all greek characters.

Besides that, the special character input was completely reworked and improved and allows you to input all greek characters and some other mathematical symbols in all text fields of Part-DB. See https://docs.part-db.de/usage/keybindings.html#special-characters

**Comment by jbtronics** [comment]
For Part-DB 1.3.1 the keybindings were changed a bit (for a more logical system) and is now properly documented. See https://docs.part-db.de/usage/keybindings.html

**Comment by blue3121** [comment]
Thank you ! Great work !!!
