### ISSUE TITLE
Show "Unknown Amount" in list, not "zero"

### ISSUE THREAD

**Issue by Tropaion** [Part-DB/Part-DB-server#282]
**Is your feature request related to a problem? Please describe.**
Currently, I you have an part with an unknown amount, it only shows that in the stock part and in the lists, it says "0"

**Describe the solution you'd like**
It would be nice if in the list it also show unknown amount, since this usually means it's not zero.
If there is a storage location with unknown amount and one with 10 parts, it would be nice to show something like 10+.
Generally it would be nice if its possible to set a stock like "10+" to indicate it's at least 10 parts.

**Describe alternatives you've considered**

**Additional context**

**Comment by jbtronics** [comment]
Fixed in Part-DB 1.3.2
