### ISSUE TITLE
Install on Debian 11, unable to get past "yarn install"

### ISSUE THREAD

**Issue by DIYsciBorg** [Part-DB/Part-DB-server#283]
Following this guide: https://docs.part-db.de/installation/installation_guide-debian.html
On a proxmox container running "Debian standard 11.3-1" template,

When I get to the step "sudo yarn install", i get the following output:
yarn install v1.22.19
[1/5] Resolving packages...
[2/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/ckeditor5/-/ckeditor5-36.0.1.tgz: connect ECONNREFUSED 2606:4700::6810:1823:443".
info If you think this is a bug, please open a bug report with the information provided in "/var/www/partdb/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Using "sudo yarn install --verbose" I get a little more.. at least can tell SOME of ckeditor dependencies pass:

yarn install v1.22.19
verbose 0.190721619 Checking for configuration file "/var/www/partdb/.npmrc".
verbose 0.191122751 Checking for configuration file "/usr/local/share/.npmrc".
verbose 0.191479732 Checking for configuration file "/usr/etc/npmrc".
verbose 0.191684514 Checking for configuration file "/root/.npmrc".
verbose 0.19188679 Checking for configuration file "/var/www/partdb/.npmrc".
verbose 0.192189225 Checking for configuration file "/var/www/.npmrc".
verbose 0.192532143 Checking for configuration file "/var/.npmrc".
verbose 0.193282316 Checking for configuration file "/var/www/partdb/.yarnrc".
verbose 0.193638122 Checking for configuration file "/usr/local/share/.yarnrc".
verbose 0.193917227 Checking for configuration file "/usr/etc/yarnrc".
verbose 0.194268179 Checking for configuration file "/root/.yarnrc".
verbose 0.194436231 Checking for configuration file "/var/www/partdb/.yarnrc".
verbose 0.19470993 Checking for configuration file "/var/www/.yarnrc".
verbose 0.194868239 Checking for configuration file "/var/.yarnrc".
verbose 0.199791119 current time: 2023-04-26T14:42:56.153Z
verbose 0.267823579 Performing "GET" request to "https://yarnpkg.com/latest-version".
[1/5] Resolving packages...
[2/5] Fetching packages...
verbose 0.77407558 Performing "GET" request to "https://registry.yarnpkg.com/@ckeditor/ckeditor5-alignment/-/ckeditor5-alignment-36.0.1.tgz".
verbose 0.780099151 Performing "GET" request to "https://registry.yarnpkg.com/ckeditor5/-/ckeditor5-36.0.1.tgz".
verbose 0.782073134 Performing "GET" request to "https://registry.yarnpkg.com/@ckeditor/ckeditor5-clipboard/-/ckeditor5-clipboard-36.0.1.tgz".
verbose 0.78419386 Performing "GET" request to "https://registry.yarnpkg.com/@ckeditor/ckeditor5-core/-/ckeditor5-core-36.0.1.tgz".
verbose 0.786350916 Performing "GET" request to "https://registry.yarnpkg.com/@ckeditor/ckeditor5-engine/-/ckeditor5-engine-36.0.1.tgz".
verbose 0.78881681 Performing "GET" request to "https://registry.yarnpkg.com/@ckeditor/ckeditor5-enter/-/ckeditor5-enter-36.0.1.tgz".
verbose 0.79162904 Performing "GET" request to "https://registry.yarnpkg.com/@ckeditor/ckeditor5-paragraph/-/ckeditor5-paragraph-36.0.1.tgz".
verbose 0.793777388 Performing "GET" request to "https://registry.yarnpkg.com/@ckeditor/ckeditor5-select-all/-/ckeditor5-select-all-36.0.1.tgz".
verbose 0.891010943 Error: connect ECONNREFUSED 2606:4700::6810:1723:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
error An unexpected error occurred: "https://registry.yarnpkg.com/ckeditor5/-/ckeditor5-36.0.1.tgz: connect ECONNREFUSED 2606:4700::6810:1723:443".
info If you think this is a bug, please open a bug report with the information provided in "/var/www/partdb/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by jbtronics** [comment]
This is no bug in Part-DB. Either there is currently some outage in the yarn repository (then it will most likely work again in a few hours), or something network related is not configured quite right on your server or network (yarn seems to be quite sensitive towards especially wrong DNS settings).

As a workaround: Here you can find zip files with the needed dependencies and built assets: https://github.com/Part-DB/Part-DB-server/actions/runs/4784970401

Just copy the content of the zip file into your  Part-DB folder (and ensure that the webserver has access permissions on them), and you can skip the steps with yarn completely...

**Comment by DIYsciBorg** [comment]
I apologize for reporting this as a bug. I got some additional advice from a co-worker regarding DNS settings. Thank you for the link. It will come in handy.
