### ISSUE TITLE
Search doesn't work for notes

### ISSUE THREAD

**Issue by iyzpx** [Part-DB/Part-DB-server#288]
**Describe the bug**
Notes doesn't seems to be searchable for the top right search bar. However, the filter at "Show all parts" works. But that needs more clicks and isn't as intuitive when trying to find something fast.

**To Reproduce**
1. Add a note to a part
2. Search that note
3. No results

**Screenshots**
![image](https://user-images.githubusercontent.com/103630942/236152655-79f89b6e-f33b-4df6-8e57-d0e0c75b13c2.png)
![image](https://user-images.githubusercontent.com/103630942/236153229-1ca706b0-be4a-43e0-9f0f-7136ebc0c8fb.png)

**Server Side**
- Part-DB Version: 1.3.2 (master/1c83691)
- PHP Version: 8.1.12
- Database Server: sqlite (3.34.1)

**Additional context**
Tested with Edge, Firefox, Chrome on Windows and Linux Mint.

**Comment by jbtronics** [comment]
Should be fixed now.
