### ISSUE TITLE
Searching with invalid regex cause 500

### ISSUE THREAD

**Issue by misaz** [Part-DB/Part-DB-server#289]
**Describe the bug**
Attemp to searching with regex option enabled fails with 500 when passed regex is invalid. Example of invalid regex is regex with tailing `\`. For example `foo` is valid but `foo\` is not.

**To Reproduce**
1. Enable `Reg.Ex. Matching` in the `Search options` menu.
2. Enter `foo\` in the search box.
3. Click `Go!` button

**Expected behavior**
Should return non-500 error code. Preferably should include humman readable description of the error.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/2937706/236859750-b00ae114-ed55-4e32-a7ae-67b0eb4a3e1d.png)

**Server Side**
- Part-DB Version: 1.3.2 (from docker image `jbtronics/part-db1`)
- PHP Version: 8.1.18 (SAPI: fpm-fcgi)
- Database Server: 10.9.5-MariaDB-1:10.9.5+maria~ubu2204 (also running in docker)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 112

**Comment by jbtronics** [comment]
This is fixed now. Instead of the 500 error, you now get a table showing you the error. Similar to this:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/5410681/236951855-31220ba2-b781-46e4-b54c-7c82e27edb12.png">
