### ISSUE TITLE
Unable to display Chinese text in the label PDF

### ISSUE THREAD

**Issue by whc2001** [Part-DB/Part-DB-server#300]
**Describe the bug**
All Chinese becomes "tofu" when rendering the labels.

**To Reproduce**
1. Go to Tools -> Label generator
2. Type some Chinese text, or referencing some parts with Chinese characters in fields
3. Click Update
4. Chinese characters in the PDF all becomes rectangle

**Expected behavior**
Should display just fine

**Screenshots**
![image](https://github.com/Part-DB/Part-DB-server/assets/16266909/323faaa2-fb9b-4b04-b356-0ece2327632c)

**Server Side**
- Part-DB Version: 1.4.1 (master/)
- PHP Version: 8.1.18 (SAPI: apache2handler)
- Database Server: 10.5.19-MariaDB-0+deb11u2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Egde
 - Version 114.0.1823.41

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by whc2001** [comment]
Seems like it's retaining the text content just fine, might be a font problem

![image](https://github.com/Part-DB/Part-DB-server/assets/16266909/2af1b653-b6b1-442a-9ec2-300a367ebfd4)

**Comment by jbtronics** [comment]
The default font family used for the labels is "DejaVu Sans" which seems to not support CJK language glyphs.
I will look into it, to include a font which supports Chinese characters (I'm not sure if I can change the default language for backward compatibility reasons, but this should be a option at least).

By the way, if you want to help to translate Part-DB into Chinese, I can add Chinese language to the crowdin translation page: https://part-db.crowdin.com/

**Comment by whc2001** [comment]
> 

Thanks, I am currently sure it's a font problem related to DOMPDF and is currently looking into a way for it to work.

And I was just about to ask you about how can I contribute to the localization! I found the XLF files but Transolution Xliff Editor is not opening it. Crowdin should make it much easier!

**Comment by whc2001** [comment]
After some attempt I finally found a working way to add new font into DOMPDF.

1. Download `load_font.php` from [dompdf/utils](https://github.com/dompdf/utils), put it in the root directory of PartDB installation
2. Grab a TTF (other format like OTF won't work) font file that you're sure it can display the characters you need. Here I copied the `DengXian` font from Windows 10 (which is definitely not free licenced and cannot be distributed) just for a test.
3. Execute `php load_font.php <FontFamily> <PathToFontFile>`, it will automatically convert and copy the font into corresponding location. Remember the `FontFamily` you have set.

![image](https://github.com/Part-DB/Part-DB-server/assets/16266909/015b03c9-4207-448b-aea9-7e7ecce1c2f6)

4. Add the following CSS directive into the `Additional styles` field of `Advanced` tab, change the value to the `FontFamily` you have set when importing the font:
```css
* {
    font-family: "DengXian";
}
```

5. Try to generate the labels again, it should work

![image](https://github.com/Part-DB/Part-DB-server/assets/16266909/da73a69b-9ad9-4e41-8b9d-5817443687b6)

**Comment by jbtronics** [comment]
This is now fixed: Part-DB now ships [GNU Unifont](https://unifoundry.com/unifont/), as fallback for glyphs not contained in the dejavu fonts. This allows to show chinese character (and almost every other unicode glyph):

<img width="497" alt="image" src="https://github.com/Part-DB/Part-DB-server/assets/5410681/65da067d-b6b6-4112-9ab7-040e6787a7e6">

The font is a bit ugly, however, so you might want to install a more beautiful one if you need to use non-latin characters regulary. This is now possible by just copying the TTF files into the `assets/fonts/dompdf` folder of Part-DB and run `php bin/console cache:clear`. Then you can use it in the CSS of the labels. See [here](https://docs.part-db.de/usage/labels.html#use-custom-fonts-for-pdf-labels) for more infos.

**Comment by jbtronics** [comment]
The fonts with unicode support are pretty huge (e.g. Noto CJK is 35MB big) and makes the pdf generation pretty slow. Because of this we dont ship these fonts but Unifont. Unifont is still pretty big (11MB), but at least offers almost full unicode support, which makes it a good fallback font.

**Comment by whc2001** [comment]
Thanks! In my opinion that's a perfect dot-matrix font for those cheap thermal label printers, since they mostly accepts bitwidth-restricted bitmap image and can cause distortion when printing small serif characters.
