### ISSUE TITLE
Editing Project BOM with duplicate item is impossible

### ISSUE THREAD

**Issue by misaz** [Part-DB/Part-DB-server#302]
**Describe the bug**
On the project overview page there is option to add new BOM item directly. This feature do not check for duplicates which make possible to make project with BOM containing one part on multiple rows. Projects containing BOM with duplicate parts are later uneditable because editing fails with error (HTTP code 422). Even deleting one itme is insufficient. User need to delete both duplicated items, save project, then add item again.

**Steps To Reproduce**
Youtube: https://www.youtube.com/watch?v=50fFDrDZjtg

**Expected behavior**
- BOM Adding Tool should check for duplicates OR
- Project edit tool should work with projects with duplicate items

**Server Side**
- Part-DB Version: 1.4.2
- PHP Version: docker
- Database Server Mariadb 10.11.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 114

**Comment by jbtronics** [comment]
This is now fixed
