### ISSUE TITLE
Database Migration from 0.5.15 fails with  " Unknown column 'perms_labels' in 'groups' "

### ISSUE THREAD

**Issue by Phiwatec** [Part-DB/Part-DB-server#304]
When running `sudo -u www-data php bin/console doctrine:migrations:migrate` as in the migration guide the migration fails with the following error:
![image](https://github.com/Part-DB/Part-DB-server/assets/52720981/ae74d637-bc36-4dbc-893e-5354a715ed5a)

I first upgraded to PartDB Version 0.5.15 as recommended in the Upgrade Guide. 
Then I followed the steps of which all except the mentioned step worked. 

Rerunning the migration on same Database results in a different error, which is okay as it is missing already migrated columns:
![image](https://github.com/Part-DB/Part-DB-server/assets/52720981/a82686e6-8783-49d8-b68d-15e701386c00)

**Server Side**
- Part-DB Version: 1.4.2 / 0.5.15-legacy  (Different folders) 
- PHP Version: 8.2
- Database Server: MariaDB 10.11.3
- OS: Debian 12

**Comment by jbtronics** [comment]
Thats strange. Is your database up to date in the legacy Part-DB? This column should have been created during older database migration in Part-DB-legacy.
I assume that this is some issue with your database (or some wrong migration in the past) and not really a migration issue of Part-DB 1.x

However your problem should be fixable, by reverting your database to the backup and running the following SQL command on the database (using phpmyadmin or command line):

```
ALTER TABLE `groups` ADD `perms_labels` SMALLINT  DEFAULT 0  NOT NULL AFTER `perms_tools`
```

**Comment by Phiwatec** [comment]
That fixed it. Thank you very much.
Greetings
