### ISSUE TITLE
Auto search / Search on typing

### ISSUE THREAD

**Issue by Phiwatec** [Part-DB/Part-DB-server#305]
**Is your feature request related to a problem? Please describe.**
In the old version of PartDB it would auto search when typing in the search bar. 
I found this feature very useful, as I could type and see if it already shows the wanted part without having to type the whole word.
Would it be possible to port this feature from the original version?
Grettings

**Comment by RaptorDE** [comment]
I noticed that this search behavior is available when I want to add parts to the BOM in a project. You can also search freely in this field. This search behavior would be great for quick searches. 

@jbtronics is it possible to bring this search field to the home page?

I tested the behavior in the demo database with this part: https://demo.part-db.de/de/parts/search?name=1&category=1&description=1&mpn=1&tags=1&storelocation=1&comment=1&ipn=1&ordernr=1&keyword=2%2C54%25X7R

![Screenshot_20240203_113328_Firefox](https://github.com/Part-DB/Part-DB-server/assets/37591931/bc1a2753-002f-40d8-85e8-449ff9ac6461)
![Screenshot_20240203_113357_Firefox](https://github.com/Part-DB/Part-DB-server/assets/37591931/48498239-e212-476f-b9be-36b2577af601)
![Screenshot_20240203_113445_Firefox](https://github.com/Part-DB/Part-DB-server/assets/37591931/1d0ab024-598e-4e4a-a626-9fe51adba145)

**Comment by RaptorDE** [comment]
I took a closer look at the search function in Project Bom and went down a ChatGPT rabbit hole 😁. The result, an additional HTML page that provides a simple, quick search. If anyone is interested, here is the [github](https://github.com/RaptorDE/part-db_quicksearch_addon).

**Comment by jbtronics** [comment]
I have implemented a proper quicksearch / autocomplete search on the navbar and the new search field on homepage:
![image](https://github.com/Part-DB/Part-DB-server/assets/5410681/001bf70f-a4f4-42ea-a68e-902199915377)


It is available in the demo instance: https://demo.part-db.de/en/

**Comment by RaptorDE** [comment]
The new search is great. Is it Possible to search for keywords in a different order than in the Description? This is possible for parts in the project BOM.
