### ISSUE TITLE
Add IPN to labelgenerator

### ISSUE THREAD

**Issue by vidarhag** [Part-DB/Part-DB-server#306]
When creating labels for parts it would be great if the IPN field was included in the LabelPlaceholder dropdown list.

![image](https://github.com/Part-DB/Part-DB-server/assets/137270856/99b4b1ec-8f09-453c-87ab-bf2e0a4e7132)

**Comment by jbtronics** [comment]
Fixed for the upcoming release of Part-DB 1.5
