### ISSUE TITLE
TypeError in MoneyFormatter::format after upgrade from v1.4.2 to v1.5.0

### ISSUE THREAD

**Issue by mindsolve** [Part-DB/Part-DB-server#311]
**Describe the bug**
After updating from 56828e9e (v1.4.2) to ac84c175 (v1.5.0), all tries to open a part result in a 500 Internal Server Error.
The server log contains the following error message:

```
{
   "message":"Uncaught PHP Exception TypeError: \"App\\Services\\Formatters\\MoneyFormatter::format(): Argument #1 ($value) must be of type string|float, null given, called in /var/www/partdb/src/Twig/FormatExtension.php on line 66\" at /var/www/partdb/src/Services/Formatters/MoneyFormatter.php line 46",
   "context":{
      "exception":{
         "class":"TypeError",
         "message":"App\\Services\\Formatters\\MoneyFormatter::format(): Argument #1 ($value) must be of type string|float, null given, called in /var/www/partdb/src/Twig/FormatExtension.php on line 66",
         "code":0,
         "file":"/var/www/partdb/src/Services/Formatters/MoneyFormatter.php:46"
      }
   },
   "level":500,
   "level_name":"CRITICAL",
   "channel":"request",
   "datetime":"2023-07-03T18:03:01.763136+02:00",
   "extra":{
      "token":null,
      "url":"/de/part/11/info",
      "ip":"10.1.1.59",
      "http_method":"GET",
      "server":"ng-partdb.ng.fx3.eu",
      "referrer":"http://ng-partdb.ng.fx3.eu/de/category/4/parts"
   }
}
```

SQL dump of the mentioned part:

| id | id_preview_attachment | id_category | id_footprint | id_part_unit | id_manufacturer | order_orderdetails_id | built_project_id |   datetime_added    |  name  |    last_modified    | needs_review |        tags        | mass | description  | comment | visible | favorite | minamount | manufacturer_product_url | manufacturer_product_number | manufacturing_status | order_quantity | manual_order | ipn |
|----|-----------------------|-------------|--------------|--------------|-----------------|-----------------------|------------------|---------------------|--------|---------------------|--------------|--------------------|------|--------------|---------|---------|----------|-----------|--------------------------|-----------------------------|----------------------|----------------|--------------|-----|
| 11 |                       | 4           | 41           |              | 290             |                       |                  | 2017-07-12 13:50:11 | 1N4001 | 2023-05-24 19:30:26 | 0            | partkeepr-imported |      | Diode 50V 1A |         | 1       | 0        | 0.0       |                          | 1N4001                      |                      | 0              | 0            |     |

SQL dump of the `orderdetails` of the part:
sqlite> select * from orderdetails where part_id = 11;
| id  | part_id | id_supplier | supplierpartnr | obsolete | supplier_product_url |    last_modified    |   datetime_added    |
|-----|---------|-------------|----------------|----------|----------------------|---------------------|---------------------|
| 743 | 11      | 1           | 1N4001FSTR-ND  | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 744 | 11      | 1           | 1N4001FSCT-ND  | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 745 | 11      | 9           | 1N4001/BKN     | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 746 | 11      | 33          | 1N4001         | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 747 | 11      | 2           | 2463391        | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 748 | 11      | 2           | 2323100        | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 749 | 11      | 11          | 18C8911        | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 750 | 11      | 10          | 2323100        | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 751 | 11      | 10          | 2463391        | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 752 | 11      | 23          | 1N4001         | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 753 | 11      | 24          | 1N4001         | 0        |                      | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |

SQL dump of the pricedetails with the above orderdetails:
sqlite> select * from pricedetails where orderdetails_id in (select id from orderdetails where part_id = 11);
|  id  | id_currency | orderdetails_id |  price   | price_related_quantity | min_discount_quantity | manual_input |    last_modified    |   datetime_added    |
|------|-------------|-----------------|----------|------------------------|-----------------------|--------------|---------------------|---------------------|
| 3969 | 1           | 743             | 135.5    | 5000.0                 | 5000.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3970 | 1           | 744             | 0.17     | 1.0                    | 1.0                   | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3971 | 1           | 745             | 0.0643   | 1.0                    | 1.0                   | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3972 | 1           | 745             | 11.94    | 300.0                  | 300.0                 | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3973 | 1           | 745             | 23.475   | 750.0                  | 750.0                 | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3974 | 1           | 745             | 40.8     | 1500.0                 | 1500.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3975 | 1           | 745             | 84.75    | 3750.0                 | 3750.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3976 | 1           | 746             | 0.02     | 1.0                    | 1.0                   | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3977 | 1           | 746             | 0.5      | 25.0                   | 25.0                  | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3978 | 1           | 746             | 2        | 100.0                  | 100.0                 | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3979 | 1           | 746             | 10       | 500.0                  | 500.0                 | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3980 | 1           | 746             | 20       | 1000.0                 | 1000.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3981 |             | 747             | 0.797    | 10.0                   | 10.0                  | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3982 |             | 747             | 5.36     | 100.0                  | 100.0                 | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3983 |             | 747             | 12.75    | 250.0                  | 250.0                 | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3984 |             | 747             | 32.4     | 1000.0                 | 1000.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3985 |             | 747             | 79.5     | 2500.0                 | 2500.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3986 |             | 747             | 109      | 5000.0                 | 5000.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3987 |             | 748             | 109      | 5000.0                 | 5000.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3988 |             | 748             | 487.5    | 25000.0                | 25000.0               | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3989 |             | 748             | 865      | 50000.0                | 50000.0               | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:36 |
| 3990 | 1           | 749             | 180      | 5000.0                 | 5000.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 3991 | 2           | 750             | 185      | 5000.0                 | 5000.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 3992 | 2           | 750             | 725      | 25000.0                | 25000.0               | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 3993 | 2           | 750             | 1200     | 50000.0                | 50000.0               | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 3994 | 2           | 751             | 1.37     | 10.0                   | 10.0                  | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 3995 | 2           | 751             | 10.6     | 100.0                  | 100.0                 | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 3996 | 2           | 751             | 13.75    | 250.0                  | 250.0                 | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 3997 | 2           | 751             | 41       | 1000.0                 | 1000.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 3998 | 2           | 751             | 85       | 2500.0                 | 2500.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 3999 | 2           | 751             | 155      | 5000.0                 | 5000.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 4000 | 1           | 752             | 0.0088   | 1.0                    | 1.0                   | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 4001 | 1           | 752             | 14.497   | 2071.0                 | 2071.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 4002 | 1           | 752             | 36.9873  | 5871.0                 | 5871.0                | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 4003 | 1           | 752             | 85.5559  | 14501.0                | 14501.0               | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 4004 | 1           | 752             | 128.1555 | 23301.0                | 23301.0               | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
| 4005 | 1           | 753             | 0.0251   | 1.0                    | 1.0                   | 1            | 2023-05-24 19:30:26 | 2023-05-22 23:05:37 |
 

**To Reproduce**
1. Upgrade from v1.4.2 with SQlite DB (I don't know whether that's relevant)
2. Open a part
3. Observe 500 Internal Server error

**Expected behavior**
I expected PartDB to display the part details.

**Screenshots**

**Server Side**
- Part-DB Version: Part-DB master @ [`ac84c175`](https://github.com/Part-DB/Part-DB-server/commit/ac84c175)
- PHP Version: PHP `8.1.2-1ubuntu2.11`
- Database Server: none, sqlite
- Server OS: `Ubuntu 22.04.2 LTS`

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Firefox
 - Version: 113.0.1

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by jbtronics** [comment]
This is now fixed in Part-DB 1.5.1
