### ISSUE TITLE
Ask for empty stock deletion

### ISSUE THREAD

**Issue by mase76** [Part-DB/Part-DB-server#327]
Hi,
I think, when the last part of a  stock was taken, there should be an option to delete the empty stock. The empty box, bag etc. does not stay in the stock most times.  Maybe a menu option, or the part taking user could be asked to delete the stock.

**Comment by jbtronics** [comment]
There is now a checkbox in the withdrawal/move modal to do this. If it is checked, the part lot which becomes empty will be automatically deleted.

**Comment by mase76** [comment]
Can I set the deletion as default somewhere? I am not sure if every user checks this.
