### ISSUE TITLE
Link to offer

### ISSUE THREAD

**Issue by pdo59** [Part-DB/Part-DB-server#330]
The field "Link to offer" in the "Purchase information" of a part, when the part is manually edited do not contain the distributor part number.
Edit a part, add a distributor, ad part number and price; in the link to offer appear the link inserted in the distributor page but there is not the part number. Even if I add the part number at the "Link to offer" after saving the part number is deleted.

- Part-DB Version: 1.6.0-dev (master/8ce5f4a)

**Comment by jbtronics** [comment]
I cannot replicate this bug. In my tests the generated link to offer contain the distributor part number.

Does your placeholder link configured on the supplier contain the "%PARTNUMBER%" placeholder?
