### ISSUE TITLE
Parts sorting

### ISSUE THREAD

**Issue by blue3121** [Part-DB/Part-DB-server#335]
Parts sorting on any field doesn't work !!!

-------------------

- Part-DB Version: 1.6.0-dev (master/5c30210)
- PHP Version: 8.1.2-1ubuntu2.13
- Database Server:  SqLite

 - OS: Kubuntu 22.04
 - Browser: Firefox
 - Version: 115.0.2 (64 bit)

**Comment by jbtronics** [comment]
This should be fixed now.

**Comment by blue3121** [comment]
Yes it's fixed !!!

Thank you !
