### ISSUE TITLE
Documentation on SAML SSO Settings needs update

### ISSUE THREAD

**Issue by drpetersen** [Part-DB/Part-DB-server#339]
The [documentation on SAML SSO settings](https://docs.part-db.de/configuration.html#saml-sso-settings) references an environment variable `SAML_SP_PRIVATE_KEY`, which [actually should read](https://github.com/Part-DB/Part-DB-server/blob/05d73d2f68fca59587c6a4f5ccbd376a2973b6c6/config/packages/nbgrp_onelogin_saml.yaml#L25) `SAMLP_SP_PRIVATE_KEY`. (Or maybe rather the latter variant is a typo?)

This is particularly hard to catch since logged error messages are not really specific (IIRC, there is a message about an invalid key, which did not really make me think about the possibility of a competely missing key), and the documentation currently points to an obsolete configuration file, `config/packages/hslavich_onelogin_saml.yaml`, which seems to have been replaced by `config/packages/nbgrp_onelogin_saml.yaml`.

https://github.com/Part-DB/Part-DB-server/blob/05d73d2f68fca59587c6a4f5ccbd376a2973b6c6/config/packages/nbgrp_onelogin_saml.yaml#L25

I hope this helps, thank you so much for this great project!

**Comment by jbtronics** [comment]
That is a actually a typo. The variables should all start with "SAML_"

I will change that.
