### ISSUE TITLE
Sorting works badly

### ISSUE THREAD

**Issue by blue3121** [Part-DB/Part-DB-server#345]
1. select a category
2. choose a sort order on any field
3. change category or reselect the same category
4. NOW the sorting returns to the name and descending BUT the indication remains on the previous selection/field

I would expect the following behavior:
Retaining the selection of the previous sort type/field

-------------------------------

- Part-DB Version: 1.7.0-dev (master/a43ee52) 
- PHP Version: 8.1.2-1ubuntu2.13 (SAPI: apache2handler)
- Database Server: SqLite 3.37.2

 - OS: kubuntu 22.04
 - Browser: Firefox
 - Version:116.0.2 (64bit)

**Comment by jbtronics** [comment]
This is now fixed and the ordering state is correct over page switching.
Will be part of the next release.
