### ISSUE TITLE
Reverse the selection

### ISSUE THREAD

**Issue by blue3121** [Part-DB/Part-DB-server#346]
Reverse the selection of the parts "on the fly" (for example with an entry in the submit box).

Thanks in advance !

**Comment by jbtronics** [comment]
In Part-DB 1.7 there will be an additional button in the action bar, to invert the selection:
<img width="797" alt="image" src="https://github.com/Part-DB/Part-DB-server/assets/5410681/7470621f-422c-4575-ac9b-5d53513855a0">
