### ISSUE TITLE
The "Associated builds part" button does not associate my project with a buids part

### ISSUE THREAD

**Issue by joseffilzmaier** [Part-DB/Part-DB-server#348]
**Describe the bug**
I am trying to associate a project with a builds part using the "add builds part" button inside the project pages "Associated builds part" category. This button opens the editor to create a new part. After creating the part it is *not* associated with the project, and in the part's "Extended info" screen the flag "Is project builds part" shows `false`.

**To Reproduce**
1. Create a project
2. Press the "Add builds part" button in the project configuration screen
3. Name the part, fill in information
4. Press the "Save changes" button
5. You will be notified that the part got created, and it did
6. The part is however not associated with the project in any way as far as i can tell

**Expected behavior**
The part should be associated with the project

**Screenshots**

**Server Side**
- Local docker image with tag `1.6.1`

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 116.0.2

**Smartphone (please complete the following information):**
 -

**Comment by jbtronics** [comment]
This will be fixed in Part-DB 1.7.0
