### ISSUE TITLE
Allow build with extra component or less

### ISSUE THREAD

**Issue by cubesky** [Part-DB/Part-DB-server#349]
**Is your feature request related to a problem? Please describe.**
I'm using PnP Machine to build the board, but sometimes PnP machine need more than BOM material, but build feature doesn't allow extra number of component, and when I make a test build with machine, it may not place all the components, but partdb doesn't allow 0 component number or not check the compoent when build

**Describe the solution you'd like**
Allow extra component number or 0 component when build.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Part-DB/Part-DB-server/assets/8038511/158e5a16-d9da-4fab-9215-e4e35b895b5c)

**Comment by jbtronics** [comment]
With the latest commit, there is a checkbox on the build parts, which disabled these quantity validations and allows to withdraw any amount.

**Comment by cubesky** [comment]
Thanks!
