### ISSUE TITLE
The env variables for TME are wrong in docs

### ISSUE THREAD

**Issue by Lopfi** [Part-DB/Part-DB-server#359]
In the docs and in the information providers page of partdb the env variables are different and I think the one in the documentation is wrong.

In documentation its PROVIDER_TME_API_KEY and PROVIDER_TME_API_SECRET
But in the code and on my instance it's PROVIDER_TME_KEY and PROVIDER_TME_SECRET

**Comment by jbtronics** [comment]
You are right, the documentation contained the wrong env name (the digikey documentation too). This should now be fixed.
