### ISSUE TITLE
Allow configuring default columns and their order using environment variable.

### ISSUE THREAD

**Issue by misaz** [Part-DB/Part-DB-server#360]
By default there are some columns preselected. I would like to change my server-wide defaults. I would like to have option for configuring

1) enabled columns
2) their order

for example:

```
PART_TABLE_DEFAULT_COLUMNS=ipn,edit,mpn,description
```

As far as I understood sources, it will require extending [PartsDataTable.php](https://github.com/Part-DB/Part-DB-server/blob/master/src/DataTables/PartsDataTable.php). Maybe some further refactoring will be needed. Currently it has hardwired defaults and order.

This can apply to other tables also, but I personaly "need" it only for parts table.

![Default columns](https://github.com/Part-DB/Part-DB-server/assets/2937706/b5a94285-1f86-4e71-96ce-20b690828f55)

**Comment by jbtronics** [comment]
This is fixed with PR #390
