### ISSUE TITLE
 Column not found: 1054 Unknown column 'perms_labels' in 'groups' 

### ISSUE THREAD

**Issue by maltejahn** [Part-DB/Part-DB-server#366]
Hi,

I am trying to move my old 0.59 installation (which i seem to have killed*) to a new server and upgrade it. The error was mentioned here #67 . Do i have to do something? 
I moved my old database to the new server, and there is the data (phpmyadmin). But when upgrading:
`php bin/console doctrine:migrations:migrate`
I get an error:
```
In ExceptionConverter.php line 67:
  An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'perms_labels' in 'groups'
```

*parts of the menu disappeared like categories. I can still search data. I dont want to waste time on the "old" version. But if there is an easy fix

**Comment by jbtronics** [comment]
This should be fixed in the latest version.

Upgrade to Part-DB 1.7.1 and revert your database to the backup before the migration attempt.
Then rerun `php bin/console doctrine:migrations:migrate`
