### ISSUE TITLE
Ability to relate parts to each other

### ISSUE THREAD

**Issue by wrightquests** [Part-DB/Part-DB-server#371]
My use case may not match the world of electronics.

The parts I track often has other parts that are exactly the same but need to be tracked separately. These are typically classified as old part number, new part number, or same part number.

Having the ability to relate parts to one another could help the chaos.

**Comment by jbtronics** [comment]
The master branch now contains the ability to relate parts with each other via "Part associations". This will be available in the upcoming Part-DB 1.9 version. 
You can try it out in the demo instance: https://demo.part-db.de/en/
