### ISSUE TITLE
Label generator: Create Barcode / QR-Code with the IPN (Internal Part Number)

### ISSUE THREAD

**Issue by Alonia123** [Part-DB/Part-DB-server#373]
Currently I have adapted PartDB so that I have 2 types of label placeholders to choose from ("Barcodes" and "Barcodes IPN"). 
The problem for me is the increased effort to perform updates, because I have to constantly check if the customized modifications 
still work.

Brief description of what I did:
----------------------------------------------------------------------------------
**BarcodeProvider.php:**
Added the following BarcodeProviders:

    [[2D_CONTENT_IPN]]
    [[1D_CONTENT_IPN]]
    [[BARCODE_C39_IPN]]
    [[BARCODE_C128_IPN]]
    [[BARCODE_QR_IPN]]

**BarcodeContentGenerator.php:**

Added getIPNContent:

**BarcodeGenerator.php:**

getContent customized -> create a barcode using getIPNContent

----------------------------------------------------------------------------------
Of course I had to do some more work here and there, but I wanted to describe briefly what I have currently done.
I would be happy if this function could be integrated into PartDB

**Comment by jbtronics** [comment]
I dont quite understand what you want to achieve with it?
So you want barcodes, where the content of the barcodes is the IPN not the generated id? Why do you need this?

**Comment by jaimelaborda** [comment]
Certainly I will also benefit of this feature, as I'm also in the same use case as @Alonia123 and I think is pretty normal to use the IPN in the industry,

**Comment by jbtronics** [comment]
I have added this feature and it will be available in the upcoming Part-DB 1.9
However, I named the placeholders `[[IPN_BARCODE_QR]]` and so on instead of `[[BARCODE_C39_IPN]]` as this naming scheme seemed more logical.

Also there is no `[[2D_CONTENT_IPN]]` and `[[2D_CONTENT_IPN]]`, as this is the same as `[[IPN]]`

**Comment by jbtronics** [comment]
With the latest commit, Part-DB scanner also supports to scan these IPN barcodes.
