### ISSUE TITLE
500 Internal Error on some part number with Octopart API

### ISSUE THREAD

**Issue by JDBertaux** [Part-DB/Part-DB-server#381]
Hi everyone,
I use Octopart API to easly import my component which fine for some component but not all. For exemple, with CRGH2512J2K2 from TE Connectivity I got an internal error 500, where F611BS106J050R from KEMET works fine. I modify nothing just click on save. 
I don't have tried with another provider yet so I don't know if it comes from Octopart or not.

The server is running under Docker (Part-DB 1.7.1) on a Synology NAS (DSM 7).

**Server Side**
- Part-DB Version: 1.7.1
- PHP Version: 8.1.23
- Database Server: 3.34.1

**Desktop :**
 - OS: Windows 11
 - Browser: Edge
 - Version: 117.0.2045.36

Can you recreate this error ?
Thanks in advance for your answers 😄

**Comment by jbtronics** [comment]
The problem was caused because the footprint returned by octopart for this element consists only of numbers, which was not possible before. (So this would happen for all providers who returned numeric only value for a element reference).

This is fixed in Part-DB 1.7.2
