### ISSUE TITLE
Octopart Error 500 When Adding New Part

### ISSUE THREAD

**Issue by eggsnblakey** [Part-DB/Part-DB-server#384]
I have Octopart integration working so that I can search for parts, but when I attempt to add the part from those search results the site generates a 500 error. I am not having this issue with the Digikey API (with Digikey I can search and add parts). Here is what is happening in the log when this happens. I have already tried clearing the Octopart entry from app.db oauth_tokens, but still getting the same issue (search works, add part doesn't). Any advice? 

{"message":"Uncaught PHP Exception RuntimeException: \"Cannot create new entity, because allow_add is not enabled!\" at /var/www/partdb/src/Form/Type/Helper/StructuralEntityChoiceLoader.php line 77","context":{"exception":{"class":"RuntimeException","message":"Cannot create new entity, because allow_add is not enabled!","code":0,"file":"/var/www/partdb/src/Form/Type/Helper/StructuralEntityChoiceLoader.php:77"}},"level":500,"level_name":"CRITICAL","channel":"request","datetime":"2023-09-27T18:15:06.649396-04:00","extra":

**Comment by jbtronics** [comment]
Is your user allowed to create entities like footprints, categories, manufacturers, etc.? (You should check the permissions for every possible datastructure)
