### ISSUE TITLE
Add "Create new part" button to top bar

### ISSUE THREAD

**Issue by RobThree** [Part-DB/Part-DB-server#394]
Would it be possible to add a "Create new part" button in the top bar?

![image](https://github.com/Part-DB/Part-DB-server/assets/607888/d1f02310-4975-4e21-b545-c09134a83761)

I am currently in the progress of entering a lot of parts (already did 1246, a few hundred more to go). I keep having to navigate to a random category or to the 'homepage' to get to the "Create new part" button. If it had a bit of a more permanent place (like my suggestion, but anywhere in the top bar will do) it would make my work much easier.

**Comment by jbtronics** [comment]
There is now a link on the left side of the navbar. Depending on your permission you can also see a dropdown menu where you can jump to parts import and import from dataprovider: 

<img width="286" alt="image" src="https://github.com/Part-DB/Part-DB-server/assets/5410681/39698d24-27b6-4aa7-abc9-3dc4d9e75a4a">

**Comment by RobThree** [comment]
You. Are. Killing. It! Great work! Thanks!
