### ISSUE TITLE
No API permissions available in settings

### ISSUE THREAD

**Issue by cooki371** [Part-DB/Part-DB-server#396]
**Describe the bug**
I am currently setting up my Part-DB server with the docker solution and when I go to the Users Tool I don't see any API settings under Miscellaneous.

**To Reproduce**
1. Login as admin.
2. Go to Tools -> System -> Users
3. Click on any User.
4. Navigate to Permissions -> Miscellaneous

**Expected behavior**
I would expect a row with API permissions.

**Screenshots**
<img src="https://github.com/Part-DB/Part-DB-server/assets/97686805/340db93f-97cc-4345-98bc-09e0dac40211" width="600px" />

**Server Side**
- Part-DB Version: 1.7.3
- PHP Version: 8.1.23
- Database Server: SQLite 3.34.1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 117.0.2045.60

**Additional context**
I am runnig Part-DB from docker in my WSL distro.

**Comment by jbtronics** [comment]
The API function is not included in Part-DB 1.7.3.
If you want to use it, you will either need to use the current master branch, or wait for the release of Part-DB 1.8
