### ISSUE TITLE
URL error when creating part from Digikey

### ISSUE THREAD

**Issue by sochartgit** [Part-DB/Part-DB-server#401]
Throws an error because the URL of an attachment contains a space.

**To Reproduce**
0. Enable Digikey as provider
1. Go to 'Tools/Create parts from info provider'
2. Search an item by filling Keyword, for example '74HCT4051 PDIP'
3. Click on the + button on a result
4. Click 'Save changes' button

**Expected behavior**
No error throwing and space character replaced by %20 for example

**Comment by jbtronics** [comment]
This is fixed now.
