### ISSUE TITLE
start in dev, allow php 8.2

### ISSUE THREAD

**Issue by tacman** [Part-DB/Part-DB-server#403]
**Is your feature request related to a problem? Please describe.**

So few applications work out of the box, but this one did!  Kudos.

Two things that I think should change, though.  Traditionally Symfony applications start out in the dev environment, rather than prod, and only when it's deployed is APP_ENV changed.  

Also, setting the PHP to 8.1 under platform in composer.json didn't work for me, but it worked fine when I got rid of that line.  I think this is because I'm using 8.2 and my version of 8.1 didn't have sqlite installed.

**Comment by jbtronics** [comment]
> Traditionally Symfony applications start out in the dev environment, rather than prod, and only when it's deployed is APP_ENV changed.

I don't really see an advantage in setting the env to dev by default. The majority of users want to run Part-DB in a non-dev enviroment, so prod is fine and needing to change the APP_ENV variable would just be an annoying task for most users.
People who need the dev enviroment should know how to change the enviornment and starting with `prod` has no real downsides. On the other hand exposes much more infos, which could lead to some unwanted information leaks to the public and maybe even direct security risks, if somebody would forget to change the env to `prod`.


> Also, setting the PHP to 8.1 under platform in composer.json didn't work for me, but it worked fine when I got rid of that line. I think this is because I'm using 8.2 and my version of 8.1 didn't have sqlite installed.

Part-DB works fine with PHP 8.2.
The platform.php setting just affects composer and the way it locks dependencies. Basically, that sets the minimum PHP version. In general the actual running of Part-DB in the webserver is not affected by the composer.json at all, as the used PHP version for the web application is determined by the webservers config.
