### ISSUE TITLE
IPN in BOM list column

### ISSUE THREAD

**Issue by cansi22** [Part-DB/Part-DB-server#418]
**Is your feature request related to a problem? Please describe.**
In my job the components are ordered from the warehouse by IPN.
When I have to look them up in the BOM, I have to open component by component to see their IPN.

**Describe the solution you'd like**
Include an IPN column and the possibility to choose the order, as in the component view.

**Comment by jbtronics** [comment]
This is now implmented in the latest master version, and will be available in the upcoming 1.9 release.
The column is hidden by default, but can be show easily using the column visibility selector.

**Comment by cansi22** [comment]
thank you very much for the quick response. 👏👏
