### ISSUE TITLE
Update docker image please?

### ISSUE THREAD

**Issue by ashlynblack** [Part-DB/Part-DB-server#422]
https://hub.docker.com/r/jbtronics/part-db/ is still on 1.7.3, docker hub says it was last updated three years ago.

**Comment by jbtronics** [comment]
Your link is the wrong docker image. That is the legacy Part-DB version from pre 1.0.

The right docker image is jbtronics/part-db1 (https://hub.docker.com/r/jbtronics/part-db1), like documented in the README.

The naming is a bit sub optimal, but for historical and technical reasons, that cannot be changed easily.

**Comment by ashlynblack** [comment]
Ohhh okay, I did use the docker-compose thing in the installation README. Google was giving me the wrong link when I searched for the image. All updated now, thanks!
