### ISSUE TITLE
DEFAULT_URL doesn't work when using Nginx to proxy PartDB as a subpath

### ISSUE THREAD

**Issue by 0x915** [Part-DB/Part-DB-server#428]
I'm using Nginx on my server to share port 80 access for multiple web services. I've proxied Part-DB to the "http://IP/part/" path and configured the environment in docker-compose.yml "- DEFAULT_URI=http://IP/part/". But when I visit http://IP/part/ Part-DB jumps to http://IP/en instead of http://IP/part/en, the former resulting in an HTTP 404.
Here is my nginx.conf snippet:
```
location /part/ {
            proxy_pass http://IP:200/;
            proxy_redirect off; proxy_set_header
            proxy_set_header Host $host; proxy_set_header X-Registration; proxy_set_header X-Registration
            proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Real-IP $remote_addr
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-For
            proxy_set_header X-Forwarded-Proto $scheme;
        }
```
I tried running cache:clear which successfully cleared the cache and removed the docker container to recreate it, failed to resolve.

Part-DB Version =  jbtronics/part-db1:1.8.2

**Comment by jbtronics** [comment]
You have to configure the prefix path by setting the `X_FORWARDED_PREFIX` header in your webserver config to the prefix value.
So you would need a line like `proxy_set_header X-Forwarded-Prefix "/part/";` in your nginx config.
I have updated the Part-DB documentation.

Also I have fixed some wrong generated pathes, when using it that way.
