### ISSUE TITLE
Location in labels

### ISSUE THREAD

**Issue by jon-daemon** [Part-DB/Part-DB-server#440]
I'm trying to create labels and add the location of my parts but it's not working.
Instead it shows[[LOCATION]] or [[LOCATION_FULL]] in the generated label.
Is it fixable? Am I missing anything?

![Screenshot 2023-11-25 at 17 25 08](https://github.com/Part-DB/Part-DB-server/assets/206048/f52f774e-0b49-4ada-bf66-9a8d6a9cfa09)

**Comment by jbtronics** [comment]
If you want to use the [[LOCATION]] or [[LOCATION_FULL]] placeholder, you need to create the label for a Part**Lot** not the part itself. That is possible by using the generate barcode button next to a PartLot.
Only the partLot contains the infos about the location, as a Part can have multiple partLots at different locations (and it would not be clear, which is one meant).
