### ISSUE TITLE
Add LCSC ELECTRONICS as API provider

### ISSUE THREAD

**Issue by binsim** [Part-DB/Part-DB-server#449]
Is it possible to add [LCSC ELECTRONICS](https://www.lcsc.com) as a provider as this is also a big electronic components distributor.

**Describe the solution you'd like**
If possible it could be added as a provider like DigiKey, ...

**Comment by Pyromane** [comment]
Perhaps we should collect the requirements for the API where, so that we can encourage the providers to implement an appropriate API.
