### ISSUE TITLE
Digikey API search error

### ISSUE THREAD

**Issue by sochartgit** [Part-DB/Part-DB-server#453]
Search engine for Digikey Provider is buggy.
When I search for BZX9C3V3, I get no result.
![image](https://github.com/Part-DB/Part-DB-server/assets/83184203/7c1db393-5c22-4950-9f8e-15d0483be39b)

But this item is available on Digikey
![image](https://github.com/Part-DB/Part-DB-server/assets/83184203/643422f3-9de5-4600-806a-7f780b928e16)

When I search for the part number from Digikey: 1801-BZX79C3V3TR-ND, I get the right result:
![image](https://github.com/Part-DB/Part-DB-server/assets/83184203/7f3d7428-d159-4ca0-8073-60cec335de47)

**Comment by jbtronics** [comment]
> When I search for BZX9C3V3, I get no result.

You are missing the required 7 here. If you search for BZX**7**9C3V3 then you get results.

In general Part-DB just passes the keyword to the digikey API and shows the results. So if the API gets no results, then Part-DB can do nothing about it.
