### ISSUE TITLE
SAML users unable to use site but able to login

### ISSUE THREAD

**Issue by msessions61** [Part-DB/Part-DB-server#504]
**Describe the bug**
SAML users are able to login and are auto assigned roles based on keycloak groups with no issue. Upon login they can only access the home page and the user info page. SAML users receive a 500 error when attempting to add new parts, go to the user settings page or do anything beyond the 2 functioning pages mentioned. On the user info page it shows their assigned role and that they should have all permissions available to admins.

Local users (users that login via username and password) are able to login the site and navigate, add parts, adjust site settings and more with no issue. New local users can be added and modified with no issue.

**Expected behavior**
For SAML users to be able to use the site to the level that their permissions allow for.

**Screenshots**
![Screenshot 2024-01-29 002955](https://github.com/Part-DB/Part-DB-server/assets/158029459/4626d002-b6cc-4665-bfb7-2b9165b7997d)
![Screenshot 2024-01-29 003031](https://github.com/Part-DB/Part-DB-server/assets/158029459/7b16b456-5c3b-4d84-a650-de9fdd382a51)
![Screenshot 2024-01-29 003100](https://github.com/Part-DB/Part-DB-server/assets/158029459/7afcbfa6-62a3-414f-9853-08edb9adf4ba)

**Server Side**
- Part-DB Version: 1.10.4
- PHP Version: 7.4.20
- Database Server MySQL 5.1.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 120.0.6099.227

**Additional context**
This instance of Part DB is being run in a docker container

**Comment by jbtronics** [comment]
What does the server logs say? They should be available via `docker logs` ?

**Comment by jbtronics** [comment]
The bug should be fixed in the new 1.10.6 release

**Comment by msessions61** [comment]
Seems to be working!
