### ISSUE TITLE
HTML entity encoding in <title>

### ISSUE THREAD

**Issue by SebDominguez** [Part-DB/Part-DB-server#505]
**Describe the bug**
When the INSTANCE_NAME has `'` for instance `Company's DB` then the title of the webpage will be `Company&amp;#039;s DB`
**To Reproduce**
1. Configure your instance using INSTANCE_NAME=Company's DB
2. Check the name of the webpage on the web browser title bar

**Screenshots**
<img width="590" alt="Capture d’écran 2024-02-01 à 09 25 54" src="https://github.com/Part-DB/Part-DB-server/assets/52816569/5ca1fe43-a199-45aa-b4aa-462c197ff926">

**Server Side**
- Part-DB Version:  1.10.6 
- PHP Version: 8.1.27 (SAPI: fpm-fcgi)
- Database Server: sqlite 3.34.1

**Desktop (please complete the following information):**
 - OS: macOS 14.2 (23C64)
 - Browser Safari 17.2 & Firefox 121.0.1 (64 bits)

**Comment by jbtronics** [comment]
This is fixed with the latest commit, and will be included in the next release version
