### ISSUE TITLE
Bug in the tree view

### ISSUE THREAD

**Issue by cAbtHelectronics** [Part-DB/Part-DB-server#506]
**Describe the bug**
It's not possible to expand a tree view completely when there is at least one node expanded. 

**To Reproduce**
Try to expend all nodes of the tree view of categories or project. The expand all function only works when the tree is fully reduced. 

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Firefox and Edge
 - Version: 122.0 and 121.0.2277.83

**Comment by jbtronics** [comment]
This is fixed with the latest commit and will be included in the next release version.
