### ISSUE TITLE
API: generating a category with parent no longer working with version 1.10.6

### ISSUE THREAD

**Issue by electronics4fun** [Part-DB/Part-DB-server#512]
**Describe the bug**
Using the API for generating a category is no longer working with version 1.10.5 and 1.10.6.
Is working with version 1.10.4

**To Reproduce**
transfered json in "/api/categories" with POST:
{"name": "Terminals", "parent": "/api/categories/3"}
(categorie id 3 is valid)

**(Un)Expected behavior**
call resonses with error code 500 (Internal Error)

**Additional context**
docker image was used

**Comment by jbtronics** [comment]
This is fixed with Part-DB 1.10.7
