### ISSUE TITLE
Added filter option: "Project"

### ISSUE THREAD

**Issue by henrikkoch** [Part-DB/Part-DB-server#516]
When looking at parts from a specific supplier as here Digi-Key it could be nice to also be able to enable filer: "Project" so you can see if you have already added that for the list on the different parts. So a request to add "Project" to the shown list - thanks.

![PartDB_feature_2024-02-11_14-52-53](https://github.com/Part-DB/Part-DB-server/assets/3817592/64322936-3e64-4725-b29d-66e884e2b98b)

**Comment by jbtronics** [comment]
This is now available with the latest commits.
