### ISSUE TITLE
Can not activete the LCSC info providor

### ISSUE THREAD

**Issue by codeman256** [Part-DB/Part-DB-server#539]
**Describe the bug**
Can not get the LCSC info provider activated.

**To Reproduce**
LCSC info provider won't activate regardless of the docker env I send it. 
PROVIDER_LCSC_ENABLED=1 or true
PROVIDER_LCSC_CURRENCY=CAD or USD or EUR

I am running part-db in docker on Unraid. All the other docker variables are working including Mouser, Digikey, database, proxy, sys vars, etc.

**Server Side**
- Part-DB Version: 1.11.0
- PHP Version: 8.1.27 (SAPI: fpm-fcgi)
- Database Server: MySQL version: 5.5.5-10.11.5-MariaDB-log

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version 

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 
 - Browser: chrome
 - Version:

**Additional context**
![image](https://github.com/Part-DB/Part-DB-server/assets/16764732/9251b0fa-8ea2-4ff6-aa36-ed57771f22cd)

**Comment by julianobst** [comment]
I can confirm that the provider is not enabled by setting the environment variables in docker env.

Environment variable is available inside the container:
![image](https://github.com/Part-DB/Part-DB-server/assets/12269611/16b84ec5-f80c-463f-ae5d-f10bb0f97e85)

Provider listed as disabled in web ui
![image](https://github.com/Part-DB/Part-DB-server/assets/12269611/cac47a8f-2d8e-4141-b8f6-bf250b88f73a)

**Comment by jbtronics** [comment]
I think the Apache config is missing the options to pass these ENVs to the webserver/Part-DB.

I will add this.

**Comment by jbtronics** [comment]
This should be fixed in Part-DB 1.11.1
