### ISSUE TITLE
Mass creation of categories fails weirdly if a categoruy already exists

### ISSUE THREAD

**Issue by nomike** [Part-DB/Part-DB-server#543]
**Describe the bug**
If I'm trying to mass create a category where one of the parents already exists, an error occurs in a weird way which doesn´t  go away until you refresh the browser.

**To Reproduce**
1. Go to 'Edit' → 'Categories'
2. Click on 'New Element'
3. Go to the 'Mass creation' tab
4. Enter the following text to create new categories:

```plaintext
Prototyping, Fabrication Products
  Solderless Breadboards
```

5. Click on "Create"
6. Click on 'New Element' again.
7. Enter the following:

```plaintext
Prototyping, Fabrication Products
  Jumper Wire
```

8. Click on "Create"

**Actual behavior**
Instead of the behavior mentioned above an error is thrown and a HTTP/500 is shown in the background of the page, behind all other controls and forms.

The page looked like this, directly before clicking "Create" in step 8.:

![image](https://github.com/Part-DB/Part-DB-server/assets/1063307/be32c9f4-aa01-4be2-b86a-cc1bff4a8ceb)

And looks like this immediately after clicking:

![image](https://github.com/Part-DB/Part-DB-server/assets/1063307/6fa97870-218f-4bd3-87e9-01c6aafce728)

Some text is white on white background which can be revealed by selecting it:

![image](https://github.com/Part-DB/Part-DB-server/assets/1063307/1a97f8c6-e37c-467b-9587-92f8d83d4ab0)

This error doesn't go away regardless of where you browse to in Part-DB. Only a browser refresh gets rid of it.

**Expected behavior**
I would expect Part-DB to create a new category named 'Jumper Wire" which is a descendant of the already existing category named "Prototyping, Fabrication Products". As this category already exists, it should be silently ignored.

If all categories specified already exist, I would also expect this to be silently ignored.

What I as a user want is for the specified categories to exist once I've clicked "Create", whether they already existed before that, I don´t care.

And even if this is not an option, if should at least show a user-friendly error message.

**Screenshots**
See above.

**Server Side**
- Part-DB Version: v.11.1.1
- PHP Version: 8.2.7
- Database Server: sqlit 3.40.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser: Firefox
 - Version: 123.0 (64-bit)

**Comment by jbtronics** [comment]
This should be fixed with the latest commit.
