### ISSUE TITLE
Bug when parsing LCSC part description

### ISSUE THREAD

**Issue by Tropaion** [Part-DB/Part-DB-server#553]
**Describe the bug**
At some LCSC parts, it is importing the HTML-Tags:
![image](https://github.com/Part-DB/Part-DB-server/assets/6797663/44163c25-6bcf-4e6a-ae14-2891f3a8b182)

**To Reproduce**
Search part...

**Expected behavior**
No HTML Tags

**Screenshots**

**Server Side**
- Part-DB Version: [e.g. Part-DB 1.0 (for dev versions commit hash is useful]
- PHP Version: [e.g. PHP 7.4.3]
- Database Server [e.g. MySQL 5.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbtronics** [comment]
This seems to happen somewhat randomly, and I could not replicate this problem. However, now manufacturers get HTML stripped too, so i think this should not happen again.
