### ISSUE TITLE
Paramters import from mouser part provider not working

### ISSUE THREAD

**Issue by Tropaion** [Part-DB/Part-DB-server#558]
**Describe the bug**
Not sure if it is intended or not, but importing parameters from the mouser part provider does not work.
With LCSC it does work nicely.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server Side**
- Part-DB Version: [e.g. Part-DB 1.0 (for dev versions commit hash is useful]
- PHP Version: [e.g. PHP 7.4.3]
- Database Server [e.g. MySQL 5.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbtronics** [comment]
The mouser API does not return part parameters / specification (or at least no useful ones) in the API.
Therefore Part-DB can not retrieve them, even if mouser has them in principle
