### ISSUE TITLE
Error during creation: Please check your inputs!

### ISSUE THREAD

**Issue by AlexD0302** [Part-DB/Part-DB-server#568]
Hello, 
I have sometimes the error that when I want to edit an existing component the 
Error message: "Error during creation: Please check your inputs!" appears. 

If I delete all "incorrect" fields, I jump back to the "Common" tab and it is still not possible to save. the changes

Does anyone have the same problem or am I doing something wrong?

**Comment by jbtronics** [comment]
What are the fields which are invalid and what message does they show?

**Comment by AlexD0302** [comment]
I mean the following fields (this is just a example and many more Parts have this strange behavior)

![image](https://github.com/Part-DB/Part-DB-server/assets/81533868/df40627c-71dd-4d16-8f12-0499abd03ad7)

Even if i delete the marked fields, the error will appear again and shows that now an other field isn't correct.

**Comment by eleinfroot** [comment]
Sorry, my english is poor :)
When i update part from information provider, saving changes is OK, but if i try to change anything after, then i got same errors as above. Workaround, not solution: delete all parameters, purchase informations and attachments and save changes. Then again update from info providers and save.

**Comment by jbtronics** [comment]
You have to delete the duplicate parameters (the ones marked red), before saving. Then the duplicate error message should disappear

**Comment by jbtronics** [comment]
You have to delete the duplicate parameters (the ones marked red), before saving. Then the duplicate error message should disappear

**Comment by jbtronics** [comment]
What part provider do You use? And what part is it?

I guess the provider returns some duplicate fields (which is not allowed).

**Comment by eleinfroot** [comment]
Yes. TME returns duplicate fields like "rodzaj opakowania", but first save is OK. Only after changing already imported information does the error appear.
![6](https://github.com/Part-DB/Part-DB-server/assets/165423450/2cf18a16-0335-45bf-82ab-e1c69d3a0141)
![8](https://github.com/Part-DB/Part-DB-server/assets/165423450/04dfc147-7a1d-4006-af2b-1298e2bf4b58)
![10](https://github.com/Part-DB/Part-DB-server/assets/165423450/d3b63dfd-bc6e-4c87-9a64-c85de0ba465e)

**Comment by d-buchmann** [comment]
Maybe it's possible - instead of filling in the duplicate parameters on part review - to add just the first parameter and join the duplicates as a comma separated list into the text field of the first one? I think little to no information will be lost that way, and ultimately the info provider (TME) is at fault here.

**Comment by jbtronics** [comment]
The validation is now performed already on part creation, meaning you can not create an invalid part (a message will be shown then). The user can then decide which value to keep.
