### ISSUE TITLE
Part-DB returns 500 error when attempting to authenticate with DigiKey

### ISSUE THREAD

**Issue by elegantiron** [Part-DB/Part-DB-server#581]
**Describe the bug**
I can't authenticate with DigiKey's API. I am able to complete all necessary steps, but when submitting the log-in information, I am redirected to Part-DB, which throws a 500 internal server error.

**To Reproduce**
1. Set up new installation (including all database migrations)
2. Configure DigiKey API (I had existing API credentials from another application)
3. Attempt to perform OAuth

**Expected behavior**
DigiKey's API OAuth toekn is stored.

**Screenshots**
![image](https://github.com/Part-DB/Part-DB-server/assets/128913032/22196ef0-3ba8-4cc5-9f13-d65c89abfb28)

**Server Side**
- Part-DB Version: 1.11.3 (official Docker image)
- PHP Version: 8.1.27 (SAPI: fpm-fcgi)
- Database Server: SQLite

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 124.0.1 (64-bit)

```
{"message":"Uncaught PHP Exception InvalidArgumentException: \"Required option not passed: \"access_token\"\" at AccessToken.php line 96","context":{"exception":{"class":"InvalidArgumentException","message":"Required option not passed: \"access_token\"","code":0,"file":"/var/www/html/vendor/league/oauth2-client/src/Token/AccessToken.php:96","trace":["/var/www/html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php:844","/var/www/html/vendor/league/oauth2-client/src/Provider/AbstractProvider.php:642","/var/www/html/vendor/knpuniversity/oauth2-client-bundle/src/Client/OAuth2Client.php:108","/var/www/html/src/Controller/OAuthClientController.php:60","/var/www/html/vendor/symfony/http-kernel/HttpKernel.php:181","/var/www/html/vendor/symfony/http-kernel/HttpKernel.php:76","/var/www/html/vendor/symfony/http-kernel/Kernel.php:197","/var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35","/var/www/html/vendor/autoload_runtime.php:29","/var/www/html/public/index.php:5"]}},"level":500,"
level_name":"CRITICAL","channel":"request","datetime":"2024-03-30T13:41:54.205101+00:00","extra":{"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/oauth/client/ip_digikey_oauth/check?code=XdAJZGBG&scope=&state=94ff677b0db35fc5a470cdd66eec9d7d","ip":"216.186.168.51","http_method":"GET","server":"inv.caprod.net","referrer":"https://inv.caprod.net/"}}
{"message":"Stored the security token in the session.","context":{"key":"_security_main"},"level":100,"level_name":"DEBUG","channel":"security","datetime":"2024-03-30T13:41:54.211449+00:00","extra":{"token":{"authenticated":true,"roles":["ROLE_USER"],"user_identifier":"admin"},"url":"/en/oauth/client/ip_digikey_oauth/check?code=XdAJZGBG&scope=&state=94ff677b0db35fc5a470cdd66eec9d7d","ip":"216.186.168.51","http_method":"GET","server":"inv.caprod.net","referrer":"https://inv.caprod.net/"}}
172.18.0.1 - - [30/Mar/2024:13:41:53 +0000] "GET /en/oauth/client/ip_digikey_oauth/check?code=XdAJZGBG&scope=&state=94ff677b0db35fc5a470cdd66eec9d7d HTTP/1.1" 500 4277 "https://inv.caprod.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
- -  30/Mar/2024:13:41:53 +0000 "GET /index.php" 500
```

**Steps Attempted**
1. Reloading the page
2. Going back and trying again
3. Clearing server cache
4. Clearing browser cache
5. Clearing both browser and server caches before retrying
6. Resetting Part-DB to full pristine condition (delete all persistent data; remove container; recreate)
7. Setting and unsetting DigiKey's OAuth2 Callback URL
8. Repeating all above steps, but this time using a new Private Browsing Session each time
9. Single, simple attempt using Microsoft Edge instead of Firefox

**Comment by jbtronics** [comment]
I can not replicate this issue. With my API credentials I can request a fresh access token and renew it without any errors.

I would suspect some kind of configuration error. Either with the API keys or on Digikey page.

Have you tried it with some newly created application keys?

Have your application key access to the "Product Information V3 - deprecated" API endpoint (you can select that in the developer portal?)

**Comment by philm001** [comment]
I can confirm that I also get this error.
Observations:

I only have the Digikey provider set. I go to the screen to look for parts from the provider. For me, this occurred when I was searching for the LTC3851 part.

I was able to get a list of parts available like normal. But, there were some differences between the Digikey P/N

For the LTC3851EGN#TRPBFTR-ND, I was able to create the part just fine.

However, for the LTC3851EGN#TRPBFCT-ND I got the error.

The differences between these two is the TR/CT. CT is the pricing for CT (The one that I want since the price breaks are from 1 to 1,000)

@jbtronics Can you try with the LTC3851 and see if you get the same results?

**Comment by philm001** [comment]
Ok so it looks like that refreshing the token helped with a different error, still getting the 500 error for some parts (LTC3851)

**Comment by philm001** [comment]
Ok so things started to magically start working again. Not sure if it takes time on Digikey servers to propagate changes to the API or what not. Still monitoring this closely

**Comment by jbtronics** [comment]
As the original issue creator has not responded again and it seems to start working again @philm001  and I could not replicate this issue. I would assume that this was maybe some temporary digikey hiccup or so.
