### ISSUE TITLE
setting value_max and value_min via API not working with 1.11.3

### ISSUE THREAD

**Issue by electronics4fun** [Part-DB/Part-DB-server#584]
**Describe the bug**
setting the parameters like described in https://docs.part-db.de/api/intro.html is only working for value_typical, not value_max and value_min.

**To Reproduce**
used repo: https://github.com/electronics4fun/smallPartDb and api given by Part-Db itself.
See example in repo line 177ff.
The typical values can be set, value_max/value_min not.
Also value_max value has a issue(or maybe it was value_min). Set manually via the Website, it can be seen in the formatted string, but not in the json (retrieved by API) as a key.

**Server Side**
- Docker Image Version 1.11.3

**Comment by jbtronics** [comment]
There were some required attributes on the `value_max` and `value_min` field wrong and missing, which caused them to not be accessible in via the API.

This is fixed with the latest commit and will be included in the next release.
