### ISSUE TITLE
Footprint autocomplete will suggest HTML elements

### ISSUE THREAD

**Issue by Gnarflord** [Part-DB/Part-DB-server#587]
**Describe the bug**
When I begin typing in the field for my KiCad footprint I will get HTML elements as suggestions:
![image](https://github.com/Part-DB/Part-DB-server/assets/19466442/44b61a5f-4feb-4b7a-8376-0db5cf9c00a9)
(Resistor_R:R_1206_3216Metric was added manually by me, I don't get any auto-completes from the default library)

Now If I empty the field I can see the whole HTML document being parsed. This is a fun way of debugging I've never encountered before :)
![image](https://github.com/Part-DB/Part-DB-server/assets/19466442/82a5dad6-a0d3-46e1-9de7-a1992b4de32d)

![Untitled](https://github.com/Part-DB/Part-DB-server/assets/19466442/000f9792-c00e-4ad0-a989-361940026111)

Now that's basically my Apache server telling me that there's a 404 error and the URL does not exist. If I look into the Apache log I see:

```
[06/Apr/2024:11:00:19 +0200] "GET /kicad/footprints.txt HTTP/1.1" 404 1137
```
Aha! I'm hosting under a subpath like `https://myurl.com/partdb` but the footprint lookup searches under `https://myurl.com` without the subpath. My Apache config for the reverse proxy looks like this:

```
<Location "/partdb">
        ProxyPreserveHost On
        ProxyPass "http://localhost:8081"
        ProxyPassReverse "http://localhost:8081"
        RequestHeader set X-Forwarded-Prefix "/partdb"
</Location>
```

Maybe I've set something up the wrong way but `X-Forwarded-Prefix` is definitely working as the page breaks completely if it's missing. But somehow `X-Forwarded-Prefix` is ignored for this particularly footprint lookup.

I have also set `DEFAULT_URI` to `https://myurl.com/partdb/` but that doesn't seem to have any impact.

**Server Side**
- Part-DB Version: 1.11.3 (via docker)
- Apache: 2.4.58-1

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox

**Comment by Gnarflord** [comment]
I have also noticed that the URLs for API access are not correct, which seems to be a related issue:

![Untitled](https://github.com/Part-DB/Part-DB-server/assets/19466442/01558f25-9d74-4706-a5ad-ec17c20db067)

### What I expect
```
Part-DB API: https://myurl.com/partdb/api
KiCad API root URL: https://myurl.com/partdb/en/kicad-api/
```
### What I got
```
Part-DB API: http://myurl.com/partdb/api
KiCad API root URL: http://myurl.com/en/kicad-api/
```

So the issues are:
- http instead of https
- KiCad API is missing the subpath `partdb` which the Part-DB API got correct

**Comment by jbtronics** [comment]
Have you set the correct TRUSTED_PROXIES env for Part-DB?

**Comment by Gnarflord** [comment]
My env contains: `TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR`
As to my understanding that basically allows connections from any address, right?

**Comment by jbtronics** [comment]
This is now fixed
