### ISSUE TITLE
Error in Installation Guide: Incorrect Database URL Configuration

### ISSUE THREAD

**Issue by hamuchan214** [Part-DB/Part-DB-server#592]
I was trying to install partdb on my server. 
https://docs.part-db.de/installation/installation_guide-debian.html
I was setting up mariaDB using the link above and it was not working correctly. I checked and found that in the MySQL/MariaDB database section under Configure Part-DB to use the new database. the value is DATABASE_URL=DATABASE_URL=mysql://partdb:YOUR_SECRET_ I found that the value is PASSWORD@127.0.0.1:3306/partdb. Perhaps the correct notation is DATABASE_URL=mysql://partdb:YOUR_SECRET_PASSWORD@127.0.0.1:3306/partdb 
I think it is a duplicate. Sorry if this is wrong.
![Direct Installation on Debian 11 _ Part-DB - 個人 - Microsoft​ Edge 2024_04_13 20_02_42](https://github.com/Part-DB/Part-DB-server/assets/104348967/f4ccb626-39b5-4bfa-aa19-b2b8710b841e)

**Comment by jbtronics** [comment]
You are right, there was a `DATABASE_URL=` too much. This is fixed now
