### ISSUE TITLE
Project-Build-Error when private lot is a subpart

### ISSUE THREAD

**Issue by cAbtHelectronics** [Part-DB/Part-DB-server#601]
**Describe the bug**
I have a Project with different subparts. One subpart got two different storage locations, where one storage location is owned by a user (A). The Problem is now that when another user (B) wants to build the project, there will appear a Server Error. Even when there are enough parts in stock for a production. I can only build as user (A) the project. 

**To Reproduce**
1. Create a part with two or more stocks
2. Give one stock, the ownership to one user, for example "user A"
3. Add this part to a BOM of a project-build
4. Build as "user A" the project -> Works
5. Login as "user B" and build the project -> Server Error 500

**Screenshots**
![Part_in_BOM](https://github.com/Part-DB/Part-DB-server/assets/60786337/5a7c186b-cb0f-412b-9092-6a91488ea522)
![ServerError](https://github.com/Part-DB/Part-DB-server/assets/60786337/408691a7-e403-4f2e-95ec-f9065f58b258)

**Server Side**
- Part-DB Version: 1.11.3
- PHP Version: 8.3.6

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Firefox 
 - Version 125.0.1 (64-Bit)

**Comment by jbtronics** [comment]
Now fixed.
