### ISSUE TITLE
About kicad‘s boom import Part-DB

### ISSUE THREAD

**Issue by QM1412** [Part-DB/Part-DB-server#604]
**Is your feature request related to a problem? Please describe.**
I want to use Part-DB to manage the project, but I got an error when importing the boom table of kicad, and I am using kicad version 8.0

**Describe the solution you'd like**
I would like to know how to properly import boom tables to Part-DB

**Additional context**
this is my boom table with kicad 8.0
![Snipaste_2024-04-26_20-51-54](https://github.com/Part-DB/Part-DB-server/assets/112964294/cfd6810d-1ab8-47e8-909a-54136aef9122)
this is my error ,if i import the boom table ,it will report this error
![Snipaste_2024-04-26_20-55-40](https://github.com/Part-DB/Part-DB-server/assets/112964294/1cd1859d-f869-421c-9bea-cffa8f0b09a8)
i don't know how to modify it

**Comment by jbtronics** [comment]
This was caused by the chinese header files (Part-DB expected english or german ones). Now the importer is language invariant, as long as KiCad does not change the ordering of the files.

**Comment by QM1412** [comment]
**I've changed the language format of the boom table, but I get the following error, what's going on**

![Snipaste_2024-05-02_12-08-34](https://github.com/Part-DB/Part-DB-server/assets/112964294/f3c1de9d-0607-4e2a-b91c-dfd0a0b7f1b4)
![微信图片_20240502120810](https://github.com/Part-DB/Part-DB-server/assets/112964294/3159a121-60f4-4221-b0e2-ebdb40674bdc)
