### ISSUE TITLE
category Parameters won't apply with new Part creation

### ISSUE THREAD

**Issue by SebastianMoewert** [Part-DB/Part-DB-server#610]
**Describe the bug**
When you define a set of parameters for a given part category, those are not automatically applied for a new part of this category.

**To Reproduce**
1. Go to Tools/Edit/Categories menu
2. Choose a part category
3. klick on the Parameters Tab
4. define a set of parameters
5. save changes
6. Go to Categories/<CATEGORY_NAME>
7. click on [+] create new part
8. switch to parameters tab
9. no predefined parameters here

**Expected behavior**
The predefined parameters appearing here would be very desireable

**Screenshots**
![grafik](https://github.com/Part-DB/Part-DB-server/assets/121216158/2860e2dd-16f1-4567-a0df-1bbd7f69416b)
![grafik](https://github.com/Part-DB/Part-DB-server/assets/121216158/12afbf01-e68e-4114-83c4-29cbe6e86ce8)

**Server Side**
- Part-DB Version: [e.g. Part-DB 1.0 (for dev versions commit hash is useful]
- PHP Version: [e.g. PHP 7.4.3]
- Database Server [e.g. MySQL 5.7]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbtronics** [comment]
The category parameters (similar to the other kind of parameters) are to define the category further and allows to specify further properties. Not the parts contained in them.
Think of a footprint, where you can specify the package sizes and things like number of pins in the parameters.

To be able to define some kind of default parameters for new parts in certain categories or so, this would be a new feature.
