### ISSUE TITLE
LCSC Search URL outdated

### ISSUE THREAD

**Issue by SapuSeven** [Part-DB/Part-DB-server#611]
**Describe the bug**
When using "Create parts from info provider" with LCSC, the search now fails with an error message.
I was able to successfully use the LCSC provider to search for parts a few days ago.

**To Reproduce**
1. Enable LCSC search using `PROVIDER_LCSC_ENABLED=1`
2. Go to 'Tools -> Create parts from info provider'
3. Input a search term and select 'LCSC' as the provider
4. Click search
5. See error

**Expected behavior**
Get search results from LCSC

**Screenshots**
![image](https://github.com/Part-DB/Part-DB-server/assets/9549504/3c0dbd3b-7a56-4fb1-8409-da4580359f75)

**Server Side**
- Part-DB Version: 1.12.0 
- PHP Version: 8.1.28 (SAPI: fpm-fcgi)
- Database Server: SQLite 3.34.1

**Additional context**
By looking at the network trace and searching on LCSC.com, it looks like the global search base url changed from /**wmsc**/search/global to /**ftps/wm**/search/global.

**Comment by Split7fire** [comment]
Any chance to release this change as point release? (may be 1.12.1?)
