### ISSUE TITLE
The “Show/Hide sidebar” button is invisible in dark mode

### ISSUE THREAD

**Issue by RaptorDE** [Part-DB/Part-DB-server#620]
The “Show/Hide sidebar” button is invisible in dark mode because it has the same color as the background.

![Show-Hide sidebar](https://github.com/Part-DB/Part-DB-server/assets/37591931/e737e5d5-0a18-4aa7-8d55-ecbc163bdf92)

Instead of just changing the color, I suggest moving the button to the navbar, as in the mobile view. As the small button on the side can easily be overlooked and is very difficult to click in desktop mode on a smartphone.

Here is an example of how it could look:

![2024-05-26 11_02_04-Part-DB – Mozilla Firefox](https://github.com/Part-DB/Part-DB-server/assets/37591931/ed92e10d-cfe8-4810-b5db-a125b31abadb)

**Server Side:**
- https://demo.part-db.de/en/
- Part-DB Version: 1.12.0
- PHP Version: 8.2.18
- Database Server 10.4.32-MariaDB

**Desktop:**
 - OS: Windows 11
 - Browser Firefox
 - Version 126.0

**Smartphone:**
 - Device: Sasung S10
 - OS: Android 12
 - Browser Chrome
 - Version 125.0.6422.72

**Comment by jbtronics** [comment]
fixed.
