### ISSUE TITLE
add scanner and search buttons to the navbar in the mobile view

### ISSUE THREAD

**Issue by RaptorDE** [Part-DB/Part-DB-server#621]
In the mobile view, the Scanner and Search buttons are moved to the hamburger menu. As these functions are frequently used on smartphones, I recommend always displaying them as buttons in the nav bar.

![2024-05-26 11_19_45-Part-DB – Mozilla Firefox](https://github.com/Part-DB/Part-DB-server/assets/37591931/0a785504-6688-45e9-a28d-e055bdabfac9)

**Comment by jbtronics** [comment]
Fixed with the merge of #622
