### ISSUE TITLE
The “Show/Hide sidebar” button tooltip is not automatically hidden after clicking it.

### ISSUE THREAD

**Issue by RaptorDE** [Part-DB/Part-DB-server#628]
![Bug](https://github.com/Part-DB/Part-DB-server/assets/37591931/fc07122e-27a4-4420-8996-6735e3a7b962)

Server Side:
- https://demo.part-db.de/de/
- Part-DB Version: 1.12.1
- PHP Version: 8.2.19
- Database Server 10.4.32-MariaDB

Desktop:
- OS: Windows 11
- Browser Firefox
- Version 126.0.1

**Comment by jbtronics** [comment]
Fixed
