### ISSUE TITLE
"MPN" is shown in "Measurement Unit"

### ISSUE THREAD

**Issue by electronics4fun** [Part-DB/Part-DB-server#630]
Webinterface: In the listing of parts "Measurement Unit" shows the content of "MPN"

![PartDb_Bug_MPN-MU](https://github.com/Part-DB/Part-DB-server/assets/23462285/1dd0158a-50e5-4bd6-90a5-5770e8245698)

**Comment by d-buchmann** [comment]
No, it's actually the "Name" of the part. Look at the part 0160-xxxx in your example.
I can confirm this behavior. One would expect the column to either contain "none"/empty field, or the name of the measurement unit if one is assigned to the part.

**Comment by electronics4fun** [comment]
uh, yes. you are right!

**Comment by jbtronics** [comment]
Fixed
