### ISSUE TITLE
--overwrite doesn't work

### ISSUE THREAD

**Issue by Gajillion** [Part-DB/Part-DB-server#635]
**Describe the bug**
partdb:backup option --overwrite should allow overwriting destination output file, even if it exists. Instead, backup fails.

**To Reproduce**
1. Run initial backup with  `/usr/bin/docker exec --user=www-data partdb php bin/console partdb:backup --full /var/www/html/var/db/backups/backup.zip`
2. `/var/www/html/var/db/backups/backup.zip` is successfully created.
3. Run another backup with the same command. 
4. Command fails immediately
```
 [INFO] Backup Part-DB to /var/www/html/var/db/backups/backup.zip

 The file /var/www/html/var/db/backups/backup.zip already exists. Do you want to overwrite it? (yes/no) [no]:
 >

 [ERROR] Backup aborted!
```

**Expected behavior**
backup file recreated in place with same name.

**Server Side**
- Part-DB Version: 1.11.3 (docker)
- PHP Version: docker installed version 4.1.27
- Database Server sqlite

**Comment by jbtronics** [comment]
Fixed
