### ISSUE TITLE
[Question] Updating Part-DB manually, i.e. without using git. 

### ISSUE THREAD

**Issue by amitzioni** [Part-DB/Part-DB-server#642]
Hey, 

I'm currently running Part-db 1.12.0 

I've installed Part-DB  not by using ```git clone```, but rather by downloading the tar.gz archive from the releases page and unpacking it.
Now I've got a notification that version 1.13 is available, however in the documentation the only way mentioned for updating is by using ```git checkout```, which doesn't work when you download the archive from the release page. 

What would be the correct way to update to 1.13 without using git ?

**Comment by jbtronics** [comment]
Bascially you have to replace all files of your existing installation with the ones from the ZIP file of the new version.

In most cases it should probably enough to delete the `src/`, `config/`, `assets/` folders from your existing installation and copy the new files over (and overwriting any existing files with it).
