### ISSUE TITLE
Bug with Parameter Input in Cell Values Using e-Notation

### ISSUE THREAD

**Issue by T0b121** [Part-DB/Part-DB-server#649]
There is an error related to parameters in specific cells where values are entered. Users can input numbers like 4.6 and 4600.6, including using E-notation (e.g., 4.6e+3 for 4.6k ohms). However, when a limit is exceeded, the issue arises. Notably, this behavior does not occur with all negative E-notations. For instance, entering 100e-9 or 0.1e-6 for capacitors results in the value being set to 0 (see images 1, 2, 3 and 4). Interestingly, attempting to enter 1 mOhm is possible with 1.0e-3 but not with 1e-3 (see images 5, 6, 7 and 8). The same problem occurs when using the German version of the website. It’s worth noting that in German notation, the thousands separator is a period (.) and the decimal separator is a comma (,), which could explain the error. This behavior persists across Firefox and Chrome, even though the images are from Chrome.

### **Images**

**1. 
![image_1](https://github.com/user-attachments/assets/7844ec7e-3b64-4358-9bc5-743586c45da9)
2. 
![image_2](https://github.com/user-attachments/assets/4e49dbd1-3caa-4bd8-8e8e-243c337fcb72)
3. 
![image_3](https://github.com/user-attachments/assets/0dd17558-db0c-46a0-9764-9a28fee9f788)
4. 
![image_4](https://github.com/user-attachments/assets/efae1925-36e2-4d5c-9187-cc9b14f5ee74)
5. 
![image_5](https://github.com/user-attachments/assets/abe26826-4b00-4c28-aa6a-ae8b9b412ef0)
6. 
![image_6](https://github.com/user-attachments/assets/605da7e6-ff33-4182-9d01-7c99b41433da)
7. 
![image_7](https://github.com/user-attachments/assets/839e220d-18fd-42cf-9092-cc372a464a4d)
8. 
![image_8](https://github.com/user-attachments/assets/47fc6cbf-59f4-4a25-b6f2-23ba4108756b)**

**Comment by jbtronics** [comment]
Actually this seems to be a bug in the symfony framework. I created a [PR in symfony for that](https://github.com/symfony/symfony/pull/57861).

Until this is merged, Part-DB 1.13.2 contains a workaround for that.
