### ISSUE TITLE
Label twig-mode: data_uri filter not found

### ISSUE THREAD

**Issue by codeaddicted** [Part-DB/Part-DB-server#665]
**Describe the bug**
when trying to create a label with twig-mode enabled i am unable to inline the generated `barcode_svg` result because of the missing data_uri plugin. the generated error is `Unknown "data_uri" filter in "lines" at line 1.`. what am i doing wrong here?

**To Reproduce**
1. Go to 'Tools' -> 'Labeldialog'
2. Enable Twig mode on 'Advanced'
3. Enter any Target ID of existing part
4. enter Content: `{{ barcode_svg("test", "QRCODE") | data_uri }}`
5. Press 'Update'
6. See Error `Unknown "data_uri" filter in "lines" at line 1.`

**Expected behavior**
A label should be generated which outputs the data url generated by the given twig commands.

**Screenshots**
![Bildschirmfoto_2024-08-04_16-30-28](https://github.com/user-attachments/assets/ecdd3f92-25cd-4687-9c8d-d2104b9b32a7)

**Server Side**
- Part-DB Version: 1.13.2
- PHP Version: 8.1.29 (SAPI: cgi-fcgi)
- Database Server: 10.5.23-MariaDB-0+deb11u1-log

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 127.0.6533.72 (Offizieller Build) Arch Linux (64-Bit)

**Additional context**
Partdb is freshly installed today (using: https://docs.part-db.de/installation/installation_guide-debian.html) no errors during installation. Using `data_uri(mime="image/svg+xml")` does not work either.

**Comment by jbtronics** [comment]
The twig extension required for the data_uri filter was not loaded into the sandboxed twig, and therfore was not available.

This is now fixed with the latest commit.

Thanks.
