### ISSUE TITLE
Use nested structures without typing parent elements

### ISSUE THREAD

**Issue by jon-daemon** [Part-DB/Part-DB-server#666]
**Describe the bug**
I'm trying to use nested structures to add or edit a category. I select a category and add the subcategory after typing '->'. The drop down list shows the new category I typed without the parent elements. If I type manually the complete path of all the parent elements it's working fine. The drop down shows the category structure correctly and I can create it.

**To Reproduce**
Create or edit a component.
Select an existing category and type -> followed by the new subcategory
Select the new category from the drop down list

**Expected behavior**
Select a category, type '->' and add a new subcategory without typing all previous parent elements

**Screenshots**
![1](https://github.com/user-attachments/assets/c33732a0-f4e0-427b-9785-2d1524559bf8)
![2](https://github.com/user-attachments/assets/93384f7b-6fe1-439d-b947-56a9d48fdfad)
In the first screenshot I typed only the category I wanted to add. In the second screenshot I typed each category.

**Server Side**
- Part-DB Version: 1.13.2
- PHP Version: 8.2.7
- Database Server sqlite 3.40.1

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Brave
 - Version 11.7

**Additional context**
The same applies for storage locations as well.

**Comment by jbtronics** [comment]
With the latest commit you can now type in "->" and it will create a new sub category based on the selected one.
