### ISSUE TITLE
Incorrect Interpretation of “Supplier Device” Package Value as Number

### ISSUE THREAD

**Issue by T0b121** [Part-DB/Part-DB-server#682]
**Description**: When entering parameters from the information sources into Digi-Key, the “Supplier Device” package value is interpreted as a number and thus entered under Type. This results in a 0603 resistor being recorded as 603. Examples can be seen in the following images:
- Image 1: 10k Ohm
- Image 2: 390 Ohm (Package 1206 right but also in the column for numbers)
- Image 3: 100k Ohm
- Image 4: 10k Ohm

This issue does not occur with “Package / Case,” where the value is correctly entered as text (see Image 5 for the 10k Ohm resistor).

I couldn’t pinpoint the exact cause of the error, but I suspect it might be related to how the value is interpreted. For instance, in Python, converting the string “0603” to an integer ignores the leading zero, resulting in “603” without throwing an error. A similar behavior might be occurring here (see Image 6 for a Python example).

**Steps to Reproduce**:
1. Enter parameters from the information sources into Digi-Key.
2. Observe how the “Supplier Device” package value is interpreted as a number and entered under Type.

**Expected Behavior**: The “Supplier Device” package value should be interpreted as text and entered correctly without ignoring the leading zero.

**Screenshots**:
- Image 1: 10k Ohm
- Image 2: 390 Ohm
- Image 3: 100k Ohm
- Image 4: 10k Ohm
- Image 5: 10k Ohm (Package / Case correctly entered as text)
- Image 6: Python example

**Additional Information**: I am not familiar with PHP, but in Python, converting the string “0603” to an integer ignores the leading zero. This might be a similar cause for the error.

Image 1
![image](https://github.com/user-attachments/assets/8fd95781-6fbc-4b55-95d0-0355ff9e66f5)

Image 2
![image](https://github.com/user-attachments/assets/99ae33f2-c385-452b-9b87-7cdae7b46971)

Image 3
![image](https://github.com/user-attachments/assets/b789ef9b-a4ef-431e-b4de-da6cc7fcaf2b)

Image 4
![image](https://github.com/user-attachments/assets/a73125cd-e540-4dd0-8951-80cfe5d44bc3)

Image 5
![image](https://github.com/user-attachments/assets/55e9d1e9-cba1-42c0-8883-05644fefc458)

Image 6
![image](https://github.com/user-attachments/assets/86e0079f-9d60-4b76-980f-a9f204e29942)

**Comment by jbtronics** [comment]
This is now fixed.
