### ISSUE TITLE
Error 500 when undeleting element

### ISSUE THREAD

**Issue by FloFaber** [Part-DB/Part-DB-server#685]
**Describe the bug**
Unable to un-delete an element. Error 500.

**To Reproduce**
1. Go to 'System -> Event Log'
2. Click on 'Undelete Element' on the according log-entry. Then click 'OK'
3. Error 500

**Expected behavior**
Element is now un-deleted.

**Server Side**
- Part-DB Version: 1.13.2
- PHP Version: 8.1.29 (SAPI: fpm-fcgi)
- Database Server: 11.5.2-MariaDB-ubu2404

**Desktop (please complete the following information):**
 - OS: Linux Mint 22
 - Browser: Firefox
 - Version: 129.0

See the log attached for more info: [partdb.log](https://github.com/user-attachments/files/16833448/partdb.log)

**Comment by jbtronics** [comment]
This should be fixed now
