### ISSUE TITLE
SSO 404 Error page

### ISSUE THREAD

**Issue by workino** [Part-DB/Part-DB-server#690]
**Describe the bug**
After the saml authentication the redirected page is wrong landing in a 404 error code.
URL: https://parts.MYDOMAIN.MY/en/saml/acs?RelayState=.......
![image](https://github.com/user-attachments/assets/08ed6b11-4dd2-4d92-975d-052a826e8e8c)

**To Reproduce**
1. Go to login page
2. Click on SSO Login
3. Authenticate against the sso provider

**Expected behavior**
To be authenticate in partsdb with my sso login

**Screenshots**
Screenshot attached before.

**Server Side**
- Part-DB Version: 1.13.3
- PHP Version: partdb docker version
- Database Server [e.g. MySQL 5.7]

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 128.0.6613.113

**Comment by workino** [comment]
Found the problem in the configuration between authentik and part-db.

Part-DB is send as GET and not post so in authentik needs to be used /application/saml/partdb/sso/binding/redirect/ instead of /application/saml/partdb/sso/binding/post/
but the answer is expected as POST. 

SAML_ROLE_MAPPING='{"admin": 1, "editor": 3, "*": 2}' is not optional so need to be set according to the group in authentik.

**Comment by workino** [comment]
It's working perfectly with authentik

**Comment by heschdy** [comment]
Hi, I'm really struggling to set authentik up. Can you share how you have configured it?

**Comment by workino** [comment]
Hello Heschdy,
In authentik the SAML protocol need to be configured like:
<img width="913" alt="image" src="https://github.com/user-attachments/assets/6a6ce71d-ee5b-4620-ac55-d99815f0927c">

and the advanced part:
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/8e67342f-3355-4e43-bdef-9babe781dd47">

I created a new certificate specifically for pertdb installation. 
NameID Property Mapping needs to be set as your username or by default will be the ID
Rest is by default.

In the .env file (I have it installed in docke) the parameters are: 
SAMLP_SP_PRIVATE_KEY=MII...........
SAML_SP_ENTITY_ID=http://PARTSDB.YOURDOMAIN.TLD/sp
SAML_IDP_ENTITY_ID=https://sso.YOURDOMAIN.TLD
SAML_IDP_SINGLE_SIGN_ON_SERVICE=https://sso.YOURDOMAIN.TLD/application/saml/partdb/sso/binding/redirect/
SAML_IDP_SINGLE_LOGOUT_SERVICE=https://sso.YOURDOMAIN.TLD/application/saml/partdb/slo/binding/redirect/
SAML_IDP_X509_CERT=MII............
DEFAULT_URI=https://PARTSDB.YOURDOMAIN.TLD/  (pay attention to have the / at the end )
SAML_ROLE_MAPPING='{"admin": 1, "editor": 3, "*": 2}'
SAML_ENABLED=true

And it will work. 
Regards
Workino :)

**Comment by heschdy** [comment]
Thanks a lot. 
Authentifikation is now working. The only problem is that the role mapping is not working. I have added the groups in the property mapping as in your screenshot. If I test it inside authentik provider I'm also seeing that the user is part of the admin group. But the user is always in the readonly group.

**Comment by workino** [comment]
As you can see my user is part of these 2 groups
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/0098bc2b-1a52-4cd4-be35-87f7e41d6820">
Just pay attention is written admin and not adminS. The rule is referring to the one without S
