### ISSUE TITLE
Can't scroll in the part merge UI

### ISSUE THREAD

**Issue by scgtrp** [Part-DB/Part-DB-server#696]
**Describe the bug**
The part merge page sometimes has `overflow: hidden` on the `<body>` element for some reason, which prevents me from scrolling down if it doesn't fit on the screen. (Sometimes it has `overflow-x: hidden;` which isn't a problem.) I am uncertain under what conditions it happens; it seems to often-but-not-always happen for me with no clear pattern.

Possibly relevant: it also has the `modal-open` class when this happens, despite no modal actually being open. (`overflow: hidden` is set directly on the element, not via the class.)

**To Reproduce**
1. Have a couple of parts with many attachments.
2. Merge them.
3. Try to scroll to the bottom of the attachments list.

**Expected behavior**
Scrolling works.

**Server Side**
- Part-DB Version: 1.14.0, from docker image (`jbtronics/part-db1:1.14`)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 130.0

**Comment by jbtronics** [comment]
This was related to the modal you are coming from in this situation. I added some javascript code, which removes it on redirection.

Therefore this should be fixed with latest commits.
