### ISSUE TITLE
Wrong translation for m_status.eol

### ISSUE THREAD

**Issue by NikoDelarich** [Part-DB/Part-DB-server#700]
**Describe the bug**
In pull request #692  the translation for m_status.eol was changed from "End of life" to "Coated", which makes no sense.

**To Reproduce**
Edit part
Expand Manufacturing status
"End of Life" was replaced by "Coated"

![image](https://github.com/user-attachments/assets/92266c99-6a9e-4043-836a-b7600b09c58c)

**Expected behavior**
m_status.eol should be translated as "End of life"

**Server Side**
- Part-DB Version: 1.14.0

**Comment by jbtronics** [comment]
Fixed with PR #703
