### ISSUE TITLE
Unable to serve under path

### ISSUE THREAD

**Issue by evg82** [Part-DB/Part-DB-server#724]
**Describe the bug**
Bad URL in queries when using under server subpath

**To Reproduce**
1. Fresh install on /part_db
2. Configure apache to serve /part_db/public as http://my_server.com/part_db

```
<VirtualHost *:80>
  Alias /part_db /part_db/public
  <Directory "/part_db/public">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>
</VitualHost>
```

3. Open browser and go to http://my_server.com/part_db
4. Click on 'Projects' or 'Categories'
5. See error
![image](https://github.com/user-attachments/assets/a2828835-0411-439f-8037-06111b2d9605)

6. 'Tools' menu works without errors

**Expected behavior**
The page load witouth errors

**Server Side**
- Part-DB Version: Last from github
- PHP Version: PHP 8.2
- Database Server mariaDB

**Additional context**
The problem I see is in some views the URL is not correctly generated and the path is duplicated.

**Comment by jbtronics** [comment]
A wrong url was generated for part tables and similar situations, when serving from a sub directory.

This should be fixed now with the latest commits (however its still recommended to put Part-DB into at a root of its own vhost)
