### ISSUE TITLE
Simple option to delete/archive obsolete parts

### ISSUE THREAD

**Issue by crazyelectron-io** [Part-DB/Part-DB-server#725]
SInce some obsolute parts are no longer relevant I would like to see a simple method to delete them fro m Part-DB, or archive them.

**Comment by jbtronics** [comment]
You can multi-select parts in a parts table and delete them all at once.

**Comment by AdrianEdelen** [comment]
You can delete parts under the tools tab for the part:
![image](https://github.com/user-attachments/assets/36540302-36dc-4212-bcb6-2a3fe4e3f63a)

**Comment by crazyelectron-io** [comment]
Ah, my bad. I completely overlooked that tab...
