### ISSUE TITLE
Install dependencies for Part-DB and build frontend

### ISSUE THREAD

**Issue by CyberTeckyLLC** [Part-DB/Part-DB-server#729]
Part-DB seems to be a great solution to use, however, I'm experiencing issues installing Part-DB using the "Direct Installation on Debian 11" method as shown on docs.part-db.de.  Installation steps work without error UNTIL I reach the "[Install dependencies for Part-DB and build frontend](https://docs.part-db.de/installation/installation_guide-debian.html#install-dependencies-for-part-db-and-build-frontend)" step, and I'm wondering if this is where the issues begin?  (See Error1.md below).

#Install composer dependencies (please note the sudo command, to run it under the web server user)
[Error1.md](https://github.com/user-attachments/files/17370990/Error1.md)

#Install yarn dependencies
[Error2.md](https://github.com/user-attachments/files/17370991/Error2.md)

#Build frontend
[Error3.md](https://github.com/user-attachments/files/17370998/Error3.md)

**Server Side**
- Part-DB Version: 1.14.0
- PHP Version: 8.3.12
- Database Server: MySQL 15.1

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye) x86_64

**Additional context**
KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q35-7.2)

**Comment by jbtronics** [comment]
For the first error, it seems that your PHP installation is missing some required extensions (more exactly `gd`, `xml` and `bcmath`).
As you are using PHP 8.3 you must not follow the installation instructions exactly (as it uses PHP 8.1), but you must install the `php8.3-` prefixed packages (so e.g. `apt install php8.3-xml` and so on).

The second and third thing are related, as the build step will not work without installing the yarn dependencies first.
It seems that the `package.json` file is somehow invalid. Maybe you still had done some changes to this file before checking out the latest version, and you are therefore stuck in a merge, which inserts additional characters to the file, which makes it invalid.

A look into the `package.json` and maybe the command `git status` should give clarity here. And a `git checkout --theirs package.json` will probably help to fix this.
