### ISSUE TITLE
"Up Arrow" blocks "Next" button

### ISSUE THREAD

**Issue by influx3k** [Part-DB/Part-DB-server#737]
**Describe the bug**
"Up Arrow" blocks "Next" button when scrolled all the way to button of page.

This is in W11, Chrome latest.

![Screenshot 2024-10-17 111041](https://github.com/user-attachments/assets/513d43e5-3742-4d4e-95ac-97aec6a8dcf5)

**Comment by Noxvil19** [comment]
The browser Opera has the same problem.

**Comment by jbtronics** [comment]
The back to top button is now a bit smaller and at a different position, so that this hopefully does not happen anymore.
