### ISSUE TITLE
SAML Users can't access the API (401)

### ISSUE THREAD

**Issue by MrBanana05** [Part-DB/Part-DB-server#765]
**Describe the bug**
Trying to access the API with an API Token created by an SAML user results into an error and a 401 response code along with an error description of "saml.error.cannot_login_saml_user_locally". This has been confirmed by multiple users, on multiple devices, using multiple different tokens and programs (Postman, the embedded `/api/docs` page, curl, ...). "Normal" users can access the API without any problems.

**To Reproduce**
1. Configure SAML SSO as described in the docs.
2. Login using SSO and create an API token.
3. Try to access some API endpoint like `/api/info` -> 401

**Expected behavior**
It is possible to use the API as a SAML user

**Logs**
```
curl -v 'https://partdb.example.com/api/info' -H 'Authorization: Bearer tcp_[...]'

< HTTP/2 401
< server: nginx/1.27.2
< date: Sun, 10 Nov 2024 15:29:05 GMT
< content-type: application/ld+json
< content-length: 0
< www-authenticate: Bearer realm="api",error="invalid_token",error_description="saml.error.cannot_login_saml_user_locally"
< cache-control: max-age=0, must-revalidate, private
< x-robots-tag: noindex
< x-content-type-options: nosniff
< referrer-policy: no-referrer, strict-origin-when-cross-origin
< x-frame-options: SAMEORIGIN
< content-security-policy: default-src 'self'; block-all-mixed-content; frame-src 'self' data:; img-src * data:; object-src 'self' data:; style-src 'self' 'unsafe-inline' data:; report-uri /csp/report
< x-content-security-policy: default-src 'self'; block-all-mixed-content; frame-src 'self' data:; img-src * data:; object-src 'self' data:; style-src 'self' 'unsafe-inline' data:; report-uri /csp/report
< x-xss-protection: 1; mode=block
< expires: Sun, 10 Nov 2024 15:29:05 GMT
< set-cookie: REMEMBERME=deleted; expires=Sat, 11 Nov 2023 15:29:04 GMT; Max-Age=0; path=/; secure; httponly; samesite=lax
< vary: Authorization
< strict-transport-security: max-age=31536000
<
* Connection #0 to host partdb.example.com left intact

```
**Server Side**
- Part-DB Version: 1.14.4 running in Docker
- Database Server MariaDB

**Desktop (please complete the following information):**
 - OS: Windows 10 / 11
 - Browser: Edge
 - Version latest
 
 - OS: Ubuntu (WSL)
 - Browser: curl

**Comment by jbtronics** [comment]
Thanks for the info. This was caused by some security mechanism which should prevent SAML users to login via local username and password. However it just checked that the authentication did not happen via SAML, so token authentication for the API triggered this mechanism.

This is fixed with the latest commit.
