### ISSUE TITLE
Cant edit SAML created users with email as username

### ISSUE THREAD

**Issue by collinkreutzer** [Part-DB/Part-DB-server#772]
**Describe the bug**
Users created via SAML may use an email address as their username. As these usernames contain an  @-symbol, the users are not editable via the PartDB administration.

**To Reproduce**
1. Login with a username containing @ symbol via SSO 
2. Login via admin account and open the edit page for the previous user
3. Press save

**Expected behavior**
Im able to edit users even if their username contains @ characters. 

**Screenshots**
![screenshot](https://github.com/user-attachments/assets/c86f823c-f19b-4ad1-bbb9-2dd90fcf6193)

**Server Side**
- Part-DB Version: 1.14.4
- PHP Version: 8.2.25
- Database Server: SQLite

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 131.0.6778.70

**Comment by jbtronics** [comment]
With the latest commits, the requirements for usernames are now lifted a bit, and the @ sign is now allowed in usernames as long as it is not first position (this is to avoid ambiguities as the @ prefix is sometimes used to denote a username).
