### ISSUE TITLE
Cached thumbnails dont work using reverse proxy

### ISSUE THREAD

**Issue by collinkreutzer** [Part-DB/Part-DB-server#773]
**Describe the bug**
Cached thumbnails (e.g. Footprint images shown in list or search view) are not displayed and have a wrong path when using a nginx reverse proxy. 

**To Reproduce**
1. Host PartDB via Docker as describered [here](https://docs.part-db.de/installation/installation_docker.html)
2. Setup nginx reverse proxy
3. Create a footprint using one of the shipped footprint images (e.g. Ceramic-SMD_0603.png)
4. Create a part using this footprint
5. Check thumbnail in list, search and detail view. List and search show no thumbnail image and have a path beginning with //localhost:8080/media/cache/thumbnail_sm/img/footprints/ instead of the correct URL. In detail view, the correct image is shown (path "/img/footprints/...".

**Expected behavior**
Path begins with / to make it relative to the hostname or uses env parameter DEFAULT_URI to construct the correct URI.

**Screenshots**
![2024-11-18 17_09_00-Parts with category Capacitor](https://github.com/user-attachments/assets/6d14a9f9-cdf0-420f-b6db-71a16c39a7ee)

**Server Side**
- Part-DB Version: 1.14.4
- PHP Version: 8.2.25
- Database Server: SQLite

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 131.0.6778.70

**Comment by jbtronics** [comment]
You are most likely missing the correct `TRUSTED_PROXIES` env, like described here: https://docs.part-db.de/installation/reverse-proxy.html

With this option, the host name is generated correctly.
